### ISSUE TITLE
北京大学第六医院 唐宏宇医生退休 目前只接受特需门诊

### ISSUE THREAD

**Issue by Lensual** [project-trans/MtF-wiki#1025]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/psyco/beijing/tang-hongyu/

### 内容

今日挂号时发现唐宏宇师生只有特需门诊号，无专家门诊。经医院电话咨询，院方表示唐宏宇医生已退休，目前只接受特需门诊。
同时唐宏宇医生特需门诊的挂号费用为900元。
![微信图片_20240524112950](https://github.com/project-trans/MtF-wiki/assets/11309551/66b604c8-154f-4eb8-8491-fb2c181356f0)

**Comment by cocoAutumn** [comment]
*sigh*...越来越离谱了喵，从疫情以前的500涨到疫情期间的800再到现在的900……
