### ISSUE TITLE
广东深圳康宁医院

### ISSUE THREAD

**Issue by UnknownUser2580** [project-trans/MtF-wiki#1030]
### MtF.wiki URL

guangdong/shenzhen-kangning

### 内容

Update: 
1. 张倩医生转去住院部了，不出门诊。问了张医生本人，回复说近半年都不会出门诊（5月27号问的）。
2. 杨惠妮医生要求的观察期必须每月都去复诊，如果没有定期复诊会不承认观察期，并要求重新计算观察期。

> 个人经历: 23年1月找的张医生开的小证说开始算观察期，后续23年4月找张医生复诊，张医生的态度是不用复诊，等观察期满要开大证了再来找她就可。
24年5月张医生不出门诊的情况下去找杨医生要求开大证，杨医生不认可张医生的说法，并要求重新计算观察期，且态度敷衍，上去就两句话直接说不认可观察期，要重新计算就让本人离开，也不关心本人近况，在和她解释张医生的说法时，很不耐烦地反复强调：“是你理解错了，还有什么事情？”。见本人一直没走，才询问本人近况以及父母态度等问题。
事后在健康160平台上咨询张医生，得到回复是可以开证，但她本人近半年不出门诊，建议有父母知情同意的书面意见后，去找位照国医生开证。杨医生的情况不知是否为个例，仅供参考。

**Comment by UnknownUser2580** [comment]
本人情况简介：
1. 23年，未开始RLE的情况下，在张医生处开到观察期的小证
2. 24年，部分RLE的情况下（工作中还是中性打扮为主，周末休息才会女装出门），被拒绝承认观察期

**Comment by SakuraRinhoa** [comment]
我在杨惠妮医生那边开过两次药，没有询问易性症相关的诊断（之前在张倩医生那边开过观察期）。但也没遇到她态度很差的情况，可能对不同人有不同态度？
张倩医生是转去住院部做总医师了，杨惠妮医生表示至少会有8个月不出门诊。
