### ISSUE TITLE
关于开设「隆乳手术」栏目的初稿

### ISSUE THREAD

**Issue by cocoAutumn** [project-trans/MtF-wiki#1057]
# 前言
MtF.wiki 建站 4 年，至今还没有像兄弟站 FtM.wiki 一样开设乳房整形手术的栏目（如 #1010 所提），推测有以下几点原因：
1. 乳房发育被认为并非 MtF 的普遍愿望（？），且作为不可逆的过程并不像「FtM 想要消灭它」一样想要获得它。
2. 乳房发育被认为可（仅在部分个体身上？）通过 HRT 实现，整形需求可能比喉结更低（然而部分个体喉结也不明显啊？）。
3. 乳房形态被认为比起其他第二性征（发型、体毛、嗓音）并非 RLE 刚需（？），且对身份和生理健康的意义都低于性腺手术。
4. 隆乳手术（以及很多简单的 FFS 比如重睑术）有大量适用于顺性别女性的资料，它们被认为可以无条件直接用于 MtF（？）。

显然这四点都很不对劲，理由如下：
1. 乳房发育得到促进对于喜爱运动的 MtF 或男性性别表达深柜的 MtF 来说可能是一种苦恼，但对大部分成年女性（包括 MtF）都应该是值得高兴的事情。
2. HRT 效果因人而异，由于口服雌二醇的效果远低于口服抗雄孕激素，MtF 很可能因过早摄入孕激素导致乳房发育上限降低。
3. 不同第二性征对 RLE 的意义因人而异，虚拟主播和闭嘴 coser 的需求侧重点显然不能一概而论。而且每个人都想补自己的短板，FFS 风险较高评价标准也较为主观。
4. SRS 的费用下限和其他门槛都更高（出境，或者境内长期精神诊断），这方面缺乏希望的个体可能选择优先在上半身投资。
5. 适用于顺性别女性的医疗资料并不能无条件直接用于 MtF，最简单的例子比如经期相关。

总之，SRS 并不是跨性别者医疗照护的终点，在收录【下面有一定主观性的内容】之前，贵站可以考虑先开设一个「如何应对关于经期的问答来避免出柜」的栏目，毕竟就学/从业单位的医疗部门由于利害关系可不适合被出柜啊。不要说什么他们有为患者保密的法律义务，这种事后救济肯定不如事先防范来的靠谱，而且真出事了取证也很难啊。

# 手术介绍
隆乳手术在实现方式上分为「自体脂肪注射填充」和「硅凝胶假体植入」两种，分别属于二级和三级整形手术（SRS 是四级），可以单独使用或搭配使用。

自体脂肪的优势是没有保质期（MtF 的结节并发症风险低于顺性别女性）且不会像假体一样仔细摸能摸出来是假体，缺点是会随时间被吸收且受成活率影响单次效果有限。

你说多次？不好意思，因为需要从大腿内侧（不够就再从腹部）取足量的脂肪，对于之前就很注重身材管理的姐妹们来说其实根本不够。本来指派男性的体脂率就偏低，如果再是个<del>舞萌痴</del>运动狂就更捉襟见肘了，BMI 小于 28 的都不用考虑（然而大于 28 的也没法 SRS 啊）。

假体的优势是一次量大管饱，缺点是有保质期（说是十年八年但可能是因为顺性别女性要哺乳什么的，MtF 说不定到时候检查不出问题就留一辈子喽）且仔细摸能被摸出来（不过能这么仔细摸咱们的人应该早就从下体或别的地方察觉我们是指派男性了吧）。

MtF 接受假体隆乳的最大阻碍可能是厚实且硬邦邦的胸大肌，因为不能像充分发育的顺性别女性一样植入在乳腺下方（如果通过 HRT 充分发育了也没必要隆乳了不是），所以往往选择术中使用内窥镜和超声刀的双平面位置（完全在胸大肌下的位置曾经也有但如今一般不再用）。

胸部柔软度本身条件比较好的姐妹（要让主刀医生面诊测量触摸确认哦）可以考虑加点钱再铺一层脂肪来改善视觉效果和表层的粗浅手感，条件不好的就不要想了，光是假体塞进去就紧绷绷的哪还有空间填脂肪啊，只会浪费钱。

假体的形状有「光面圆形」、「毛面圆形」、「毛面水滴形」三种，选择的依据如下：
1. 水滴形只有一条对称轴所以在植入时不能旋转，对医生要求较高（当然经验丰富的肯定能做好）。
2. 虽然圆形的少女感更佳，但产后妇女等本来就下垂的女性不适合圆形，否则会出现「最凸的点不是乳头」的尴尬情况。
3. 对于乳头离锁骨较远而离下皱襞较近的部分 MtF（下皱襞就是测量下胸围的水平线与乳房半圆相切的切点），圆形假体可能也会有上述情况，虽然仍可考虑圆形，但退而求其次的做法是选择重心不是特别靠下的短水滴形。
4. 胸部条件较差的 MtF 选择光面假体做双平面植入会有摩擦力不足滑下去的风险，毛面会好一些。

除了形状以外假体还有大小和凸度的区分，可选择的大小取决于个体自己的底盘大小（太大了会更容易被看到和摸到边缘），实际选择还取决于个体的穿搭需求（受职业影响，夜店公主和坐班柜员能一样吗）和胸部条件，太大或高凸的可能会很紧导致恢复期更痛苦。

部分个体术前可能存在双侧乳房大小不对称的情况，如果差别不是特别大的话不建议通过一对大小不对称的假体去修正。

手术切口分为乳晕、下皱襞、腋下。
1. 乳晕切口对顺性别女性来说会影响哺乳，对 MtF 来说也容易伤到组织。
2. 下皱襞切口的疤痕较为明显，但医生操作难度小，术后恢复也比腋下更快。
3. 腋下切口对于有腋毛的个体来说可以完美隐藏疤痕，但术后恢复期较长（相当长一段时间不能抬举上臂，不知道最终能否恢复到术前水平），而对喜欢穿露肩无袖装的姐妹来说可能就不太好？

最后就是医生的经验了，尽管隆乳手术的医生往往也常做面部尤其是鼻部整形，但选个从业二十年的副主任医师应该足够了。

关于价格，这取决于假体是国产的还是进口的（但效果和安全性方面医生才是最重要的！），德国和美国货都挺不错，美国货两个系列较便宜的一个中最贵的也比国内皮瓣 SRS 要便宜。

境内男证接受隆乳手术有一定医学伦理风险（比如需要家属知情或知情同意），但私立医美比起公立没有那么怕医闹，而且也不像专做性别肯定医疗的那些医生一样那么怕被上级施压（真被叫停了受害的是广大兄弟姐妹），所以应该还好。

# 手术过程
以笔者为例，在某连锁私立医美选择了美国某短款水滴形，腋下切口，安排在当天上午的第一台手术（隆乳这种大手术在私立医美尽量争取到医生精神状态最好的第一台）。  
术前一周之内需要完成血常规、凝血、胸部 CT、乳腺彩超、心电图等体检。  
术前一夜入院，各种问卷问诊（女证被问到经期就出柜吧），测量拍照，22 点后禁止饮食，不用像下体手术一样进行痛苦的肠道准备真是太好了。  
手术当天主刀医生画线，插留置针后在假体包装盒的塑封外用马克笔签名，然后全麻受术。  
术中需要用到内窥镜、超声刀、传送袋（避免医护人员直接接触假体，同时也方便冲洗术腔）。  
刚苏醒时可能会感觉胸部把最近一两个小时的挨刀过程快进播放了一遍，但不会很疼。  
根据出血情况，幸运的话可能不需要插引流管（它的疤痕还是很讨厌的）。  
关于导尿管，如果术前一整天的脱水工作做的很扎实，那么苏醒后几个小时之内是不会有尿意的，随后完全可以在有人帮助的情况下下床去洗手间。  
这一点很重要，因为从阴茎插的话拔的时候会很痛苦，从 SRS 人造的尿道口插则可能因为和顺性别女性解剖结构差异而有被插坏掉的风险。  
总之我因为向麻醉医生出柜而被免除了插导尿管，出院前要多下几次床就是了（或者穿成人纸尿裤，但卧姿排尿容易使不上劲），可不要因为这个而不敢喝水啊。  
上午第一台手术的话，晚餐就可以喝粥吃煮鸡蛋了（但是根据全麻体质差异，可能会当场呕吐并在会在半夜复发全部吐掉），次日开始午饭可以直接吃普食，只要不吃辛辣刺激和发物就行。  
术后第三天出院，在这之前（包括手术当天和出院当天共计四天）每天都有三瓶液体要输，均通过留置针进行，液体成分并不会引起疼痛。  
出院当天会被套上一个 ∞ 形状的束乳衣，毛面假体受术者需要穿戴两周。  
饭量和食材控制得当的话可以做到出院前不用大便，毕竟用力排便时胸部也会跟着疼啊。  
术后前一到两周，受术者可能都难以独自从平板床（不同于可以倾斜床面的病床）上起来或安全地躺下，尤其是半夜被疼醒想去洗手间时。如果能有人陪护那就太好了。  
术后一周复诊拍照对比，可以开始洗澡但上半身的水温必须低于体温。

未完待续……

**Comment by Cryolitia** [comment]
> MtF.wiki 建站 4 年，至今还没有像兄弟站 FtM.wiki 一样开设乳房整形手术的栏目（如 https://github.com/project-trans/MtF-wiki/issues/1010 所提），推测有以下几点原因

原因很简单，只是因为没有人投稿这方面内容，我不反对添加此类内容。

> 但对大部分成年女性（包括 MtF）都应该是值得高兴的事情。

不建议代表其他人

> 贵站可以考虑先开设一个「如何应对关于经期的问答来避免出柜」的栏目

此类内容更适宜在 RLE.wiki 展示，我个人不反对（只要有人写）

**Comment by clansty** [comment]
> 如果一个女性从青春期起就一直平胸那么恐怕不会「不以为憾反以为傲」吧？

我们应该注重于“自己怎么想”而不是“一个普通女性**会**”怎么想

**Comment by clansty** [comment]
> 但感觉除了校园指南以外的部分其实还是应该 MtF 和 FtM 分离开？

不过这是包含很多个人色彩的（ugc）内容，MtF Wiki 还是更注重收录那些普适的没有情感的内容

以及与其讨论这些，不如直接开始制作内容。毕竟要收录的内容是和用户怎么想无关的，如果有需求的话可以参考的内容。

**Comment by saeziae** [comment]
~~lgbt~~ lgtm, u pr, i merge

**Comment by Cryolitia** [comment]
> 很久没去了，刚瞅了一眼感觉发展的很不错，但感觉除了校园指南以外的部分其实还是应该 MtF 和 FtM 分离开？

考虑到你wiki的受众，投稿人员，维护者有一大批的酷儿流性别乃至两性畸形之类的TGD群体，简单粗暴的划分成MtF/FtM是几乎不可能的。

**Comment by cocoAutumn** [comment]
> u pr, i merge

新开栏目对目录结构有要求，没有单文件 pr 那么简单，我只能停留在 issue 层面，你们加油。
> 简单粗暴的划分成MtF/FtM是几乎不可能的。

FtM.wiki 面向的对象包括但不限于
1. FtM（出生时 指派性别为女性 的 跨性别男性）
2. FtX（出生时 指派性别为女性 的 非二元性别者 或 性别酷儿）
3. XtM（出生时 为间性别者，后确立了男性认同）

…及有关心的人是前几种的人。

所以至少可以划分成男性倾向跨性别者（transMasculine，tM）和女性倾向跨性别者（transFeminine，tF），毕竟两类人往往「一类想到的内容另一类看了会诱发 GD」。

**Comment by Catherina0** [comment]
> > 如果一个女性从青春期起就一直平胸那么恐怕不会「不以为憾反以为傲」吧？
> 
> 我们应该注重于“自己怎么想”而不是“一个普通女性**会**”怎么想

普通女性就一定认为平胸是遗憾吗？这辈子为了自己活，别去管这个世界的那些条条框框。

**Comment by saeziae** [comment]
> > u pr, i merge
> 
> 新开栏目对目录结构有要求，没有单文件 pr 那么简单，我只能停留在 issue 层面，你们加油。

行，我找个时间整理一下
