### ISSUE TITLE
建议重新评估宛平南路600号的可用性

### ISSUE THREAD

**Issue by Pichuworks** [project-trans/MtF-wiki#1064]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/psyco/shanghai/shmhc/

### 内容

20240722携对象去开证，陆峥转刘娜，刘娜的态度恶劣（预定所谓“受亚文化影响”的论调以此进行审问），问的问题也毫无专业程度可言，直接导致当场惊恐发作（早上的量表结果甚至还挺好的，下午真的是好端端的人差点没了，之前数月的抗抑郁/焦虑治疗进度可能需要重置），建议重新评估宛平南路的可用性
详细链接：http://xhslink.com/dgqnAQ
p.s. 另有报道，30岁大龄党也被刘娜要求强制带家长

**Comment by Pichuworks** [comment]
另外现在新规：
![e17ab22daafcf5d4d1a85abe7fa2972b](https://github.com/user-attachments/assets/6219daa4-9c1b-4b99-83f1-5ceaae9b361a)
现在陆峥不怎么管事了，王飙也不会签字

**Comment by AnnaBeiyan** [comment]
> 另外现在新规： ![e17ab22daafcf5d4d1a85abe7fa2972b](https://private-user-images.githubusercontent.com/7061249/351437141-6219daa4-9c1b-4b99-83f1-5ceaae9b361a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3OTE3NTAsIm5iZiI6MTcyMTc5MTQ1MCwicGF0aCI6Ii83MDYxMjQ5LzM1MTQzNzE0MS02MjE5ZGFhNC05YzFiLTRiOTktODNmMS01Y2VhYWU5YjM2MWEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjRUMDMyNDEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTE5NzIyYmUxM2ZiNTg2YTkzNDY4M2U5NzVkYzk5MjE1MDI4OTIzYTMxMDVmZDU4ODAyMDY1NzZkM2EwODc4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Squ3soYHGV0X8IauHIeIUXXk3m2lUme_zoxJzbQyM6I) 现在陆峥不怎么管事了，王飙也不会签字，找陆峥会直接转到刘娜，并且据说新规之后几乎没有一次下证的说法了

来源请求

**Comment by canyie** [comment]
来源为：https://mp.weixin.qq.com/s/E-DQjoGFbStYqQ6Fe2lntQ
暂不确定真实性

**Comment by AnnaBeiyan** [comment]
如果新规属实要修改的话看起来要有比较大的改动，但是似乎目前仍然有声称“没有观察期”的反馈，是否考虑暂时继续观察一段时间。如果没有后续反馈的话那么看起来是应该彻底拿这个公众号文章重写大部分相关内容，并增加一些对应说明。

**Comment by Cryolitia** [comment]
建议转移至 #856 讨论
