### ISSUE TITLE
陈臻的嗓音训练价格有所调整

### ISSUE THREAD

**Issue by DaiZiLing** [project-trans/MtF-wiki#1091]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/vocal-therapy/chen-zhen/

### 内容

八月中旬通过小红书联系到陈臻教授的助理，前往上海仁树耳鼻喉科现场问诊后，付款时的价格是 10600 CNY/疗程，半个疗程五次课的价格则是 5300 CNY
![QQ截图20240820201136](https://github.com/user-attachments/assets/995d8de8-567a-49a0-956c-32c1639ff3d5)

**Comment by QIJIUnot79** [comment]
仁树收费略有不同，会偏贵，9月在陈臻处嗓音训练10次价格依然为7900CNY

**Comment by Leetfs** [comment]
> 仁树收费略有不同，会偏贵，9月在陈臻处嗓音训练10次价格依然为7900CNY

感谢反馈，将于近日更新。

**Comment by Leetfs** [comment]
我们近期接到了陈臻先生本人的邮件投稿，稿件中要求将其出诊地点改为长宁区精神卫生中心，故暂时仅收录长宁区精神卫生中心。
