### ISSUE TITLE
精神科医生 河北医科大学第一医院 安翠霞

### ISSUE THREAD

**Issue by ziniuguo** [project-trans/MtF-wiki#1155]
### 医院名称

河北医科大学第一医院

### 医生姓名

安翠霞

### 注意事项

河北的证特别难开，大部分医生要么不开要么会把你批判一番，安翠霞是唯一一个友跨的。小证没什么难度，直接和医生说就可以开了。医生会让你自诉，直接说自己的状态就可以了（我直接把回龙观的病历给医生让她抄去了）。我在回龙观就诊过，所以只是为了在回龙观拿大证而交叉诊断。医生态度非常友好，我感觉只要成年的话不带家长也可以随便开。

大证必须要去河北医科大学第一医院精神卫生中心申请多学科专家联合会诊，但我觉得基本不太可能开的下来，因为不友跨的医生太多了，因此我也没有尝试。

病历上可能会在初诊后面有一个问号，需要的话可以让医生把问号去掉。

安翠霞只在特需，主楼二楼的国医堂，不在精神卫生中心，因此挂号需要去特需门诊，300一次。

### 证明样式

![photo_2024-10-07_12-58-27](https://github.com/user-attachments/assets/1891655a-6f3b-4c12-99ce-17afb4e98ce2)

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by ziniuguo** [comment]
any update?

thanks

**Comment by Leetfs** [comment]
您好，感谢贡献。

但收录医生需满足以下条件：

- 医生对开证有清晰的条件，医生本人知晓开证是在干什么。医生了解诊断证明乃手术条件之一，知晓开证可能会被家长闹事。
- 医生本人愿意接诊更多跨性别。
- 明确只有能开诊断证明的精神科才有收录的必要。

参考链接：[贡献者指南-MtF.wiki](https://mtf.wiki/zh-cn/docs/contributor-guide/)
