### ISSUE TITLE
广西壮族自治区南宁市第五人民医院罗隽医生

### ISSUE THREAD

**Issue by xiazhen0333** [project-trans/MtF-wiki#1184]
### 医院名称

南宁市第五人民医院（南宁心理医院）

### 医生姓名

睡眠障碍病区罗隽医生

### 标签

需要家长介入

### 注意事项

问诊细节：

- 医生会询问何时开始发现自己的跨性别者身份，是否开始HRT，有什么样的表现以及期望
- 询问是否有其他心理问题以及家长态度
- 询问目前的工作学习状况 

注意事项：

- 罗隽医生较为关注家长态度，如**家长态度不明确/不支持则不会进行下一步的诊断**（包括其他心理问题），且之后态度会变得敷衍，会被以各种理由打发
- 睡眠障碍病区诊室就诊人数多，会有大量待就诊患者聚集在门前，建议注重保护隐私

笔者情况：

- 有抑郁等心理问题且大多在发展期
- 家长目前为不支持态度

补充：医生会建议你先脱离家长再进行下一步的打算（对于家长不支持者），**如有类似情况的建议不要前往该医生处就诊，有极大可能会恶化你目前的情况**

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by AnnaBeiyan** [comment]
您好，请问当前是否有该医生诊断证明的开具条件的相关信息，谢谢！

**Comment by xiazhen0333** [comment]
> 您好，请问当前是否有该医生诊断证明的开具条件的相关信息，谢谢！

- 需要家长陪同且家长态度支持
- 成年
