### ISSUE TITLE
青岛 | 何兰杰

### ISSUE THREAD

**Issue by Lodolala** [project-trans/MtF-wiki#1191]
### 医院名称

山东大学齐鲁医院（青岛）

### 医生姓名

何兰杰

### 标签

提供 HRT 指导, 有检查项目

### 可开具的药品

戊酸雌二醇, 螺内酯, 其他

### 注意事项

# **挂号**
- 使用「[山东大学齐鲁医院青岛院区](https://open.weixin.qq.com/qr/code?username=qlyyqd)」微信公众号小程序进行挂号
- 每日早 8 时放 14 天后号。例：周一早上放两周后周一的号
- 每日早 7 时，下午 13 时额外放出若干当日对应半天号源
- 初次挂号需要建档，使用身份证在公众号上进行实名登记
- 何兰杰的号比较难抢，记得提前挂，貌似不接受加号
> 注意：找何兰杰进行咨询前必须先在同院高进医生处进行就诊，并由高进医生向何兰杰医生进行告知后再前去就诊，如果直接挂号并前去就诊可能会被婉拒
# **就诊**
若高进处已告知，则会直接询问需求并开具处方，不需要诊断证明
> 医院没有色普龙，只有补佳乐和螺内酯，比卡鲁胺尚不清楚
若有诊断证明也可直接开具处方
所有的检查一般会在高进医生处做完，不需做另外的检查
# **注意事项**
- 何兰杰医生是大内科主任医师，只有专家号，**挂号费较贵（200元）**
- 医生可能会给予诸如「自购激素药物并定期监测」的建议（笔者就是这样）
- 目前医院政策改为最早预约挂号时间前半小时内报到进入排队，不需太早到院
- 可以用医保
- 诊室隐私还可以，比较安静
- 就诊前一定先到护士站对面的报到机报道，否则不会叫号
# **出诊时间表**
- 每周三，周四出诊

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Cryolitia** [comment]
@ModestJoker4691 高进倒是去年就跟我说打算联系内分泌科开HRT来着，真搞成了挺好。
