### ISSUE TITLE
程明医生表示未成年人无法开证

### ISSUE THREAD

**Issue by lfsjww** [project-trans/MtF-wiki#1220]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/psyco/hunan/cheng-ming/

### 内容

在今年暑假去找了程医生，其表明未成年无法开证，并表示龙智医生未成年也无法开具HRT处方

**Comment by Leetfs** [comment]
已交叉核实，据开过的人反馈：“23年时就要求成年才能开了”。

**Comment by Cryolitia** [comment]
已经我本人确认。

Acked-by: Cryolitia PukNgae <Cryolitia@gmail.com>
