### ISSUE TITLE
泰国对我国公民旅游提供60天免签

### ISSUE THREAD

**Issue by ImogeneAdderley** [project-trans/MtF-wiki#1249]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/friendship/

### 内容

自2024年7月15日起 泰国对我国公民赴泰旅游提供60天免签 （之前为30天免签）
信息来源 微信公众号 泰王国驻华大使馆
![mmexport1733662629110](https://github.com/user-attachments/assets/c0c9018b-769e-4536-9e52-c6b06603a284)

**Comment by Cryolitia** [comment]
@ImogeneAdderley 可以确认，我确实是被批准逗留了60天。
