### ISSUE TITLE
更新新的贴片

### ISSUE THREAD

**Issue by estranho998** [project-trans/MtF-wiki#1254]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/medicine/estrogen/estradiol-patch/

### 内容

新的雌二醇贴片，在淘宝，京东，拼多多上均有售有售，笔者和身边的人使用后的性激素六项报告已经可以确定该药物有效，但是仍旧缺乏更多个体的情况。
商品名：Esttramon ®
厂商：HEXAL/赫素制药（暂时未找到官网，如果有官网信息补充多加感谢）
规格：50、75、100 µg/天
说明书：https://cs8.camscanner.com/sync/dl/358/761B0EF1E72243C6Lf7LS9X1.pdf
附带盒子正面图片
![IMG_9240](https://github.com/user-attachments/assets/50c64f84-ee15-4c2b-9e9a-24798e45b886)

**Comment by Bersella-AI** [comment]
已确认此产品系德国 Hexal AG（山德士全资子公司）所制，官网为 <https://www.hexal.de/>，产品页面：<https://www.hexal.de/produkte/estramon/estramon-100-mcg-24-stunden-transdermale-pflaster/>。可以考虑收录。

另据说明书所述，100 µg/d 贴片可达到 C<sub>avg</sub> 81 pg/mL，C<sub>max</sub> 118 pg/mL。是否方便提供实际检查结果？

**Comment by estranho998** [comment]
可以提供，该是本人两贴片且第二天的情况。朋友的激素水平截图无，记忆中是两贴片第三天150+ng/ml。个人认为皮下吸收的个体差异极大，难以有个具体标准。只能根据个体的性激素六项水平进行调整，不过起始使用建议以一贴的第三天进行测量，可能这个数据比较有参考性。还有贴片贴在除小腹以外的地方相当容易掉，甚至因此出现过脸上出油和勃起的类似反雄症状，测量是这点也需注意。
两贴第二天，前一天早晨服用了12.5mg色，下午3点左右测量，空腹
![79A50EF0-DDCF-4BEB-AF71-E06F8C59E966](https://github.com/user-attachments/assets/6f6ca192-2679-419f-a4fd-35d9448f1328)

**Comment by estranho998** [comment]
鉴于个体差异极大，也建议将用法用量表述如下：

据 Estraderm® 说明书，一份 0.1 mg/天（100 µg/天）的贴片可将雌二醇血药水平平均增加 67 pg/mL；与基础雌二醇相加后基本可满足 [HRT 建议范围的下限](https://mtf.wiki/zh-cn/docs/medicine/monitoring/)（100 pg/mL 左右）。低于此剂量的可能不适用于已成年的 MtF。一般每周建议使用两片（Estrana® Tapes 为每两日一片）。但是，由于透皮吸收具有极大的个体差异性，甚至有少量报告单片可能达到极大的血药浓度，请以自身具体情况灵活调整剂量，防止更多潜在风险。

**Comment by Bersella-AI** [comment]
用法方面，我打算这么修：

> **谨遵医嘱或说明书使用。** 一般每周使用两片（Estrana&reg; Tapes 为每两日一片；Climara 为每周一片），贴于大腿内侧、臀部或腹部（臀部稍好于腹部）。贴敷时可正常游泳、沐浴，无需事先取下。\
> 以上所示理论疗效取自专家说明书，仅供参考，而且每个人之间的疗效也不尽相同；应以实际验血结果为准。采用一张 100 µg/天的贴片时，叠加内源的雌二醇，有可能实现 **HRT 建议范围的下限**（100 pg/mL 左右）；低于此剂量的可能不适用于已成年的 MtF。

然后将各说明书所示的理论血药水平挪到各品牌贴片介绍之下。你后面这句十分到位，我会考虑加进去的。

此外可能还需要注明，由于检测方法可能存在差异，实际验血结果（普遍采用化学发光法——免疫测定法的一种）和临床研究、说明书所示的结果（多采用色谱/质谱法）可能有明显差别[^1]——根据我和 @ChisakaKanako 的讨论。

[^1]: Yin Y, Ma C, Yu S, et al. Comparison of three different chemiluminescence assays and a rapid liquid chromatography tandem mass spectrometry method for measuring serum aldosterone [J]. *Clinical Chemistry and Laboratory Medicine*, 2020, 58(1): 95-102. <https://doi.org/10.1515/cclm-2019-0706>

**Comment by estranho998** [comment]
> 此外可能还需要注明，由于检测方法可能存在差异，实际验血结果（普遍采用化学发光法——免疫测定法的一种）和临床研究、说明书所示的结果（多采用色谱/质谱法）可能有明显差别[1](#user-content-fn-1-2ad0e549273c4dd345d764334013753d)——根据我和 @ChisakaKanako 的讨论。

我给人认为如果需要加入的话，至少需要证实其确实有差异。国内有没有使用质谱法检测的医院？我考虑去试一下在同一天跑两个医院检测雌二醇浓度确认一下，去证实一下相关信息。

**Comment by Bersella-AI** [comment]
> 我给人认为如果需要加入的话，至少需要证实其确实有差异。国内有没有使用质谱法检测的医院？我考虑去试一下在同一天跑两个医院检测雌二醇浓度确认一下，去证实一下相关信息。

尚不清楚。已知我本人和 @ChisakaKanako 迄今做的激素六项检测均基于化学发光法，但她透露“曾检出 49.71 ng/L”，申诉回馈是“机器损坏”，换用另一台检测原理不同的机器复验，结果“不足 30 ng/L”；但是，报告单上没有写明用了何种方法，所以不能确定。关键是“复验”，即同一时间采集的血样做了两次检验，这样可以排除采样时间不同造成的干扰，所以要尽可能在同一家医院做。（但该怎么开口呢……）

**Comment by Bersella-AI** [comment]
分开抽血的最大问题是雌二醇代谢快，虽然贴片给药稳定，但一个小时后也免不了有波动，那就不好比较了。有条件一起测的医院估计少之又少。

我还找了另一篇综述，说是尽管免疫法看上去不那么精确，但也有足够的临床意义，只要高于 40.8 pmol/L（11 pg/mL）[^1]；况且，雌二醇以外的其它雌激素也并非完全没有雌激素效力。现在想来，实际操作中应该无需过分关注检测方法上的细节，无需另开 issue，也不必在正文里强调。

[^1]: Taylor A E, Keevil B, Huhtaniemi I T. Mass spectrometry and immunoassay: how to measure steroid hormones today and tomorrow [J]. *European Journal of Endocrinology*, 2015, 173(2): D1-D12. <https://doi.org/10.1530/EJE-15-0338>

**Comment by Bersella-AI** [comment]
于上个 commit 加入了 Estramon 并修订用法，现将关闭此 Issue。

**Comment by NoMTF** [comment]
<img width="1272" height="813" alt="Image" src="https://github.com/user-attachments/assets/ff52170a-8bec-4a77-8fcc-ca53d1e19b8a" />
太猛了这个 两片小腹（三天前晚上）今天（下午两点）测六项直接470
我一直使用这个贴片hrt，两天一换
这玩意绝对比说明书牛逼的多
（笔者半年前睾丸切除 仅用贴片hrt 身高175体重140体脂20，肝肾功能均无问题，血脂凝血均无问题，不抽烟不喝酒不od，无遗传病史）
