### ISSUE TITLE
关于上海九院的诊断以及检查时间的反馈

### ISSUE THREAD

**Issue by VocodexElysium** [project-trans/MtF-wiki#621]
如题，本人在8月16日星期二前往整复外科程医生处，被告知整复外科并不在周二提供hrt相关服务（包括开具必要的检查，原因似乎是由于hrt相关单次就诊时间就要至少半小时，可能会影响普通门诊的进行），hrt相关统一在周六的跨性别门诊接受就诊，wiki上写的非周六就诊相关内容可能已失去实效性（一方面，空腹抽血仅设在上午进行，而程医生在下午出诊，另一方面，普通门诊无法开具骨密度相关检查）。特别地，程医生指出，九院医疗序列团队需要的仅是检查报告结果，并不强行规定做检查的医院，因此可以提前在wiki上得知需要做检查的项目，在当地做完检查后携带报告直接前往跨性别门诊。

**Comment by septs** [comment]
考虑到局部修改会造成全文自洽性问题，建议您重新修改后发起 PR 以便于接受。

**Comment by Rinfair-CSP-A016** [comment]
此issue内容当前是否仍有效？@VocodexElysium
