### ISSUE TITLE
2022年8月北京回龙观医院就诊情况及过时内容报告

### ISSUE THREAD

**Issue by ArielHeleneto** [project-trans/MtF-wiki#623]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/psyco/beijing/bhlgh/

## 关于医院

医院比较偏，请考虑13号线到回龙观站后骑行8min自行车到医院。该医院没有对外食堂，对内食堂医生们都不吃（大概是没时间）。最近的有吃的地方在1km外，请考虑自备伙食。

## 挂号篇

- 建议使用京医通挂号，号较多而且方便；可以在0说话的情况下完成挂号到问诊的内容。
- 候补队列在前一天1800截止，如果此时没有成功候补，则会退费；候补队列没有任何用处，至少本人测试两次没有挂到号；
- 由于未知原因，该系统会在就诊当日早上放出**当天**的两个号，时间未知，原因未知。（该内容存疑，[邸晓兰](https://www.haodf.com/doctor/11007.html)主任说的）本人成功在就诊当天早上0735挂了一个一号。
- 由于COVID-19，外地且该城市有中高风险地区的同学请挂号前准备**48h**核酸阴性证明截图，微信联系**京医通**人工客服解除限制，防止该系统提示诸如系统错误等信息导致挂号失败。
- 该系统可能由于缓存问题，请不要相信医生界面上的有号的提示，一切以挂号界面为准。（当然点击有号的按钮可以跳转）
- 由于该院的排队策略的原因，建议无脑抢第一个能挂的号
- 如果已经有尚未问诊的成功挂号订单，不能候补

### 牛雅娟

本人第一次挂的牛雅娟老师的号，需要注意以下内容。

- 挂号费 100 CNY
- 如果挂星期一的抑郁症专家门诊，牛老师会拒绝问诊并要求你挂星期三的号，但是可以先开检查（检查项目附后）
- 有一个王姓研究生~~挂件~~，初诊会由该医生在独立诊室问诊，书写病历并作出处置（就是开检查单）
- 如果时间紧张，牛雅娟医生会同时问诊两个病人（其中一个由上述王医生接待），类似流水线作业。
- 在王医生做出处理后，（检查完成后），牛会带着王一起问诊并做出诊断，如果情况复杂，会主动要求你次日（也就是星期四）早上非常早来医院联系邸晓兰医生问诊处理，如果有条件建议两个医生一起挂。情况简单的立即出病历。
- 如果她认为需要，会按照病历上的电话主动联系（是她本人的私人电话，请勿骚扰回拨），有一定几率主动加微信回访（别想着看朋友圈，里面没东西）。
- 如果她认为需要，会将相关内容通知王医生和邸晓兰医生，并电话/当面告知，要求你次日早上来。（王医生会将病情报告给邸晓兰，并在次日和邸晓兰一起出诊）

#### 收费项目

以下内容无特别说明，均是单项收费支持微信支付宝自助。报告均当场出。名称以导诊单上内容为准

- 挂号费 100 CNY
- 初建门诊病历 2 CNY（该项用于建立门诊大病历，缴费后凭身份证到二楼病案室建立档案。会要求你在导诊单背面写联系人填家属名字，电话填自己的，理由见上文）
- 心率变化测定 50 CNY
- 眼动检查（EM） 42 CNY
- 明尼苏达多项个性测验 170 CNY
- 症状自评量表（SCL-90）测评 64 CNY
- 焦虑自评量表测评 14 CNY
- 抑郁自评量表测评 14CNY
- 防御机制问卷（DSQ）测评 28 CNY
- 压力评估量表测评 14 CNY
- 威斯康星卡片分类测验（WCST）45CNY
- 瑞文推理测验 28CNY
- 生活时间评定量表（LES）测评 28CNY
- 强迫症装问卷（YALE-BROWN）测评 34CNY

导诊单上有检查室位置。

### 邸晓兰

该医生速度较快，建议在牛问诊后再去以节约时间。同时该医生会在病历上书写你的获奖信息和“聪慧”的相关内容，请拍照时注意。

## 关于复印病历

携带身份证联系导诊台，要求其开申请，然后拿到病案室要求复印，复印完毕后将会出具收费条，按照页数收费（0.4CNY一张），然后拿着收费条去一楼窗口缴费（只支持现金，不推荐100大钞找零），然后拿着收据回到二楼病案室取病历，最后到导诊台敲章。

建议一次性复印全部内容，这样你可以获得检查报告的复印件。

**Comment by ArielHeleneto** [comment]
另外考虑到时间问题，建议在准备好后在二楼自助机取号（签到），特别是号码较小的同学（一号）

**Comment by Master-Hash** [comment]
我今天复印病例时并没有收费，据说是“暂时”不收。流程一致。

**Comment by septs** [comment]
> 2021年初就诊时16周岁，在回龙观医院取得京医通实体卡时未被要求提供家长身份证。
> 16周岁以下有待考证(?

from #660

**Comment by Cryolitia** [comment]
2022.11.17就诊，未收取病历复印费

**Comment by ArielHeleneto** [comment]
确认2022年12月就诊时未收取病例复印费（据他们说暂时不收了）

**Comment by Rinfair-CSP-A016** [comment]
这个“暂时”实在耐人寻味了属于是（x

**Comment by Cryolitia** [comment]
@Rinfair-CSP-A016 322..20 未收

**Comment by ArielHeleneto** [comment]
> 这个“暂时”实在耐人寻味了属于是（x

但是反正复印收不收钱是小事情（

**Comment by Cryolitia** [comment]
@ArielHeleneto 如果只收现金就是大事了（

**Comment by Cryolitia** [comment]
目前仍未接到恢复收取病例复印费的报告，目前可认为暂不收取。

本 Issue 将关闭，如有任何未尽事宜欢迎重新打开。
