### ISSUE TITLE
依照 SRS FAQ (v1.1) 重新整理 

### ISSUE THREAD

**Issue by septs** [project-trans/MtF-wiki#630]
依照 [SRS FAQ (v1.1) · Fluorescence - 知乎](https://zhuanlan.zhihu.com/p/480695175) 重新整理

https://github.com/mtf-wiki/MtF-wiki/blob/master/content/zh-cn/docs/srs/srs-faq.md
https://github.com/mtf-wiki/MtF-wiki/blob/master/content/zh-cn/docs/srs/srs-tech.md

**Comment by Cryolitia** [comment]
CC @flouria

**Comment by Cryolitia** [comment]
CC @fluoria （似乎是一个人）

**Comment by fluoria** [comment]
> CC @fluoria （似乎是一个人）

嗯，这个没有什么问题，相关内容可以随意使用。
