### ISSUE TITLE
零深度是否可以通过司法鉴定以及司法鉴定标准的问题

### ISSUE THREAD

**Issue by ljtjerry** [project-trans/MtF-wiki#634]
MtF.Wiki->欢迎->SRS 性别重置手术->术后护理
这一页面的“Q/A章节”有这么一句话：“目前的部分医生要求或司法/医学性别鉴定仍然需要跨性别女性（尤其是术后归国的）的阴道具有一定深度和宽度。”

然而
MtF.Wiki->欢迎->SRS 性别重置手术->证件变更指引
这一页面的“B”司法鉴定章节，则说
“鉴定过程：法医隔间现场检验外观，不检查内部。”

那么在泰国做的零深度手术，是否可以通过司法鉴定并改证呢？有关这方面的（即“委托事项：鉴定本人第一性征为女性”）鉴定标准，目前有官方文件么？还是说就看做鉴定的法医自己的标准？

**Comment by saeziae** [comment]
「法医隔间现场检验外观，不检查内部。」就是零深度也可以的意思，一般也就是看一眼然后套模板填空。目前也没有收到因零深度而无法鉴定报告。

目前对于什么是「女性性征」没有明文规定。

但是，我们也不能绝对排除少数医生会刻意检查深度的可能。

**Comment by septs** [comment]
我认为这个问题上没有一个稳定的结论，毕竟司法鉴定的最终决定权来自鉴定机构

**Comment by caihongxianzi** [comment]
今年发布的新版《性别重置技术临床应用管理规范》将2017年版中的“完成符合转换性别后的外生殖器重建手术后，医院为手术对象出具有关诊疗证明，以便手术对象办理相关法律手续。”改为了“完成符合转换性别后的生殖器及性腺（睾丸、卵巢）切除手术后，医院为手术对象出具有关诊疗证明，以便手术对象办理相关法律手续。”
因此，目前国内零深度SRS应该可以改证。至于国外做的零深度是否也可以改，似乎还缺乏真实案例。

**Comment by caihongxianzi** [comment]
国外有的医院似乎还不知道国内的规定改了，说零深度的在中国不能改证

**Comment by Cryolitia** [comment]
现场观察，复旦大学上海医学院法医鉴定中心使用的鉴定标准是SF/T 0111-2021

**Comment by Cryolitia** [comment]
会分为三项询问是否切除阴茎阴囊，是否外阴成型，是否阴道成型及深度，暂不清楚后两项回答否会对鉴定结果产生何种影响。其他询问和观察事项包括精神科首诊及确诊记录，激素使用史，喉结，乳房，体毛，服装，皮肤，声音等。若喉结切除术后需提供相应医院材料。

**Comment by Cryolitia** [comment]
@Cryolitia 有报告称周法医处零深度可以通过鉴定

**Comment by Cryolitia** [comment]
close https://github.com/project-trans/MtF-wiki/commit/19afc9b314049795b8e1fab33ab159f791823945

**Comment by Master-Hash** [comment]
> 已经基本可以确认零深度甚至仅切除可以通过复旦大学上海医学院司法鉴定中心周法医处司法鉴定，但是可能需要较高的女性化程度。
> 
> https://archive.md/20230816141059/https://www.xiaohongshu.com/explore/64d9eb4d000000000c036886
> 
> ![image](https://private-user-images.githubusercontent.com/23723294/261038837-4ecc7398-24c3-46e9-ac5f-07bca5affb22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzYyOTcsIm5iZiI6MTcwMzIzNTk5NywicGF0aCI6Ii8yMzcyMzI5NC8yNjEwMzg4MzctNGVjYzczOTgtMjRjMy00NmU5LWFjNWYtMDdiY2E1YWZmYjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA5MDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2M2IyYTRkZmJiNzA4NWFiYWQ1YTkxMWY5NDhjNmY0Njk4ZGZkY2NhYmJjNjY4MzkxYTIxOTYwMWEwZmZhMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dIv5LSwUxYjoS9UVWOh1t4fXI2lmjfw24GuK7Tc2O6E) ![image](https://private-user-images.githubusercontent.com/23723294/261038972-7bbe3704-1962-4253-af15-a0386bb5c757.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzYyOTcsIm5iZiI6MTcwMzIzNTk5NywicGF0aCI6Ii8yMzcyMzI5NC8yNjEwMzg5NzItN2JiZTM3MDQtMTk2Mi00MjUzLWFmMTUtYTAzODZiYjVjNzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA5MDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNzRlOTljNGVkYmQ4MWE4MjI5YmQzZmFmYjVlN2NkOWU5ZDc0Y2QwNzQyNTBiYTYyMTZiOWU1YmZiMTg3OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2oDXZV-9CQ8w9D0eqHKFsJ2pmVqvz2tZbpohGkmXM-s)

请问“可能需要较高的女性化程度”具体是多高？
