### ISSUE TITLE
北大六院相关

### ISSUE THREAD

**Issue by Honoka55** [project-trans/MtF-wiki#650]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/psyco/beijing/cong-zhong/
https://mtf.wiki/zh-cn/docs/psyco/beijing/tang-hongyu/

### 内容

- 与北京大学第三医院官方简称为北医三院的格式不同，北京大学第六医院的官方简称为北**大**六院，相关表述建议更改。
- 丛中医生与唐宏宇医生的出诊时间可能需要更新。我至少在周四下午看到了丛中医生出诊，在周一下午看到了唐宏宇医生出诊。不知道哪里可以查到完整的最新出诊时间表。
- 关于证明样式：初诊假条上的诊断不再为“易性症？”，而是“性别不一致？”。
- 唐宏宇医生对社群略有微言。透露社群接触情况不影响开证。

**Comment by ArtsEpiphany** [comment]
感谢投稿！

- 「北京大学第六医院的官方简称为北大六院」已证实，稍后更新
- 丛中医生疑似停诊，待进一步确认
- 关于证明样式：欢迎提供最近的假条图片，我们会进行更新。**请注意隐私保护**，如果没有信心，可以发送邮件至hi@mtf.wiki，而非在github上直接发布图片
