### ISSUE TITLE
部分价格似乎已过时

### ISSUE THREAD

**Issue by caihongxianzi** [project-trans/MtF-wiki#676]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/srs/china/pku3/

### 内容

我从潘柏林医生科普号上得到的参考价格如下：
一、生殖器手术
1、睾丸切除术：1万元
2、单纯阴茎阴囊切除术（“零深度”阴道成形）：4万元
3、阴茎阴囊皮瓣翻转阴道成形术：7-8万元
4、带蒂乙状结肠阴道成形术：5-6万元（未包含阴茎阴囊切除）
二、乳房手术
1、假体隆胸术：5-6万元（根据假体选择而浮动）
2、自体脂肪注射隆胸：4-5万元（根据目标体积浮动）
3、乳头扩大术：12000元（双侧）
4、乳晕扩大术：12000元（双侧）

因此“费用约50000人民币”的说法似乎已过时。

**Comment by septs** [comment]
作为一个被动接收信息更新的站点，跟踪价格这个事情总是发生在被发现价格发生变化并且得到报告时

建议合并至 #669 做进一步的讨论

**Comment by Cryolitia** [comment]
waiting for upstream
![image](https://github.com/project-trans/MtF-wiki/assets/23723294/263a2997-db66-4eb4-acad-4f3380385f8c)

**Comment by Cryolitia** [comment]
closed this as [completed](https://github.com/project-trans/MtF-wiki/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/project-trans/MtF-wiki/commit/371756b8a7c1ca73bfe5d3f438285fad220dd464 [now](https://github.com/project-trans/MtF-wiki/issues/745#event-10078142892)
