### ISSUE TITLE
湖北省武汉市精神卫生中心，李赋医生就诊过程中遇到的问题

### ISSUE THREAD

**Issue by ljtjerry** [project-trans/MtF-wiki#683]
基本情况：27岁，初诊成功开证

遇到的问题：
1. 医生跟我讲，他最近很困惑，因为最近因为跟我相同原因就诊的人突然增加了好多。所以个人推测，不排除未来有收紧开证条件的可能性。
2. 医生会询问就诊者是否在其它地方就诊过。如果回答“是”，则会要求查看当时的病历资料。如果没带，或者不想给医生看的话，这个问题回答“否”要更好一些。本人幸亏是手机里保存着病历资料的照片，不然的话这次初诊就开不了证了。
3. 医生还是会看就诊者的外貌特征的。比如会询问我的头发是否是假发。（emmmm，可能是我的头发比较长）

**Comment by ljtjerry** [comment]
![qq_pic_merged_1669457693015](https://user-images.githubusercontent.com/13274938/204083654-9abf90d2-2641-45ca-ac6c-217ef7ce6c83.jpg)
![qq_pic_merged_1669457739775](https://user-images.githubusercontent.com/13274938/204083656-b14082d3-e780-400a-a1a7-d2fd276c0735.jpg)
4、请在拿到证后务必确认诊断书上的信息是否正确，对于比较pass的人，可能会给你张女证（

**Comment by Officeyutong** [comment]
补充一下，去找李医生的话最好带着能证明“性别焦虑影响到了生活”的材料（比如之前去看抑郁、焦虑的病历，或者家长支持，或者吃药吃了好几年的证明之类的），要不然会被以材料不足拒掉

**Comment by XiangYyang** [comment]
btw最好说明自己的激素使用情况（比如因为各种烦烦所以自己尝试恰激素啊），按照咱3个月前的情况来说
医生似乎并不在乎Mf分，但是似乎很关注你自己性别认同带来的影响。
12月2日我再去时医生还主动提及关于自己用激素所带来的影响，等等的。那天医生也给咱说过最近有很多（我）这样的同类来找他

**Comment by machine-doll** [comment]
现在那边似乎不给开证了，李赋这段时间都没有排班，而且我去问了一下别的医生，无论是大证还是小证现在似乎都不给开了。牵扯到“性身份”的都要由专家评估，但是并没有那个“专家”。  
另外，前几个月（大概4月）开始收紧。通过率不高。感觉以后应该会完全不给开
