### ISSUE TITLE
SRS医生信息更新：上海长海医院-赵烨德

### ISSUE THREAD

**Issue by Hanaajanen** [project-trans/MtF-wiki#694]
### 以下补充数据均为2022年11月更新
撰写距离手术时间40天，术式为皮瓣。
信息较散，需要重新组织进原文。
赵博技术今年突飞猛进，术后文字评价和效果图将在术后稍晚时候(晚于六个月)更新。
### 前置条件
1.当前手术排期约为七个月，赵博每周可以做两台mtf的手术。
2.易性证证明在入院后会被收走，如果想要收藏的话建议事先复印
3.需要无犯罪记录证明，承认电子版/截图
### 费用构成
1.入院后会被建议在术中使用新的液态涂料来填充皮瓣与造口间的空隙，花费6,216RMB（该条具有时效性）.
2.护工费用单独收取，100RMB/d. 
3.术中术后医院方的总花费（不包括前几条）约50k，因人而异（例如体重不同用的麻醉量不同等）。准备60k可以满足所有开支。
### 入院准备
1.凡士林纱布需要用粗网，避免买错浪费资金。
2.防疫期间现已**不允许陪护**进入病房，只能在电梯间陪伴。若想陪护只能_自己也进去一起做并央求院方安排到一个病房。_
### 手术和术后准备
1.禁水时间为术前一晚21:00以后（而非术晨4:00）
2.术晨不再需要肌注术前针。
3.术后换药分别在（以手术当天为第0天则）day3,6,9,11，第3天拔负压引流管，第12天拆包下地，d14拔尿管拆线。
4.要求吸氧7天，心电监测1天（到次日晨），有充电需求需要提前准备好。
5.该层护工只有两人，结束禁食后经常出现护工难以及时响应需求的状况。
6.术后三天内(day0-2)给予止痛泵且允许肌注杜冷丁安眠。

**Comment by ArtsEpiphany** [comment]
感谢投稿！另外，手术排期具有时效性，因此不适合放在wiki上

**Comment by cocoAutumn** [comment]
<img width="440" alt="QQ20221216-211009@2x" src="https://user-images.githubusercontent.com/88474935/208105600-1aa66478-147a-42a0-84df-591963f09957.png">
经与赵烨德医生本人微信联系确认，上海长海医院SRS对无犯罪记录证明要求的有效期为一年，较北医三院等的半年更长。
另外电子版的无犯罪记录证明一般是附有二维码的，可以留意一下。

**Comment by septs** [comment]
@cocoAutumn 似乎在不主动询问时不会索要该项材料

**Comment by sceext2** [comment]
窝前几天 (2022年12月) 也刚刚在此医院手术, 目前还没出院.  手术排队实际总时长 411 天 (2021-10-28 开始).  

预计几个月后补充手术相关信息.  ;-)

**Comment by sceext2** [comment]
目前病房已经停止每天的新冠核酸检测, 并陆续出现阳性感染者, 并且医护工作人员阳性之后仍然需要继续正常上班.  

但是, 手术之前仍然需要保证核酸阴性, 否则将无法手术 (直接被出院).

**Comment by Hanaajanen** [comment]
@cocoAutumn @septs 我和我未婚妻同期手术(10.26/28)，我开到无犯罪记录证明并且发给了赵博，她因为邮寄原因送不过来（亦没有电子版），最后没发，也没什么影响。可能主动询问也不会索要该材料吧（

**Comment by cocoAutumn** [comment]
@sceext2 https://github.com/mtf-wiki/MtF-wiki/issues/592 我在此医院的面诊甚至早于在411，411的排期结果为7个月（2208-2303）。

**Comment by Rinfair-CSP-A016** [comment]
由于信息已失去时效性，此issue将关闭，如相关内容仍需要更新至wiki请reopen该issue

**Comment by Cryolitia** [comment]
@Rinfair-CSP-A016 滚一边去，别碰我工作

**Comment by Cryolitia** [comment]
预征询 
请问 @Hanaajanen  是否需要在主线提交中添加您为 [Co-Author](https://docs.github.com/zh/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors)，如果需要的话请提供您的电子邮箱地址，详见Github帮助，非常感谢。
