### ISSUE TITLE
关于未成年自切药药的求医记录

### ISSUE THREAD

**Issue by sourceoflife123** [project-trans/MtF-wiki#702]
### 本人情况说明

> 本人于2022年7月26日在安徽合肥自切，今年15周岁，马上就要16周岁了，父母因我有抑郁症而支持我并说18以后给我SRS，然而我发现了不对劲且抑郁发作，同时在学校补习时被发现日常上女厕所被警告，所以自切。自切后暂且在某不知名小医院治疗，因最先看国家说只切除生殖器及性腺（没错我牛子也切了）就可改性别，所以去安徽医科大学第一附属医院处找张贤生本打算只做尿道改口，哪知安徽省这方面政策和国家大方针有一定区别（医学鉴定不需要公证就可以改身份证但是必须做SRS才能改证），后在该院联系整形外科会诊试图找赵宇(张说他可以SRS)进行SRS，但他们说必须18周岁，之后通过安徽医科大学关系找到安徽医科大学第二附属医院整形外科曹东升，本来说好好的，但是因为 1某些原因本说10月份可以手术但推迟到12月份后又推迟至1月份 在我向我爸妈说"安徽这方面技术太差了，我们去其他地方做吧"以后，他们先是很生气我怎么要求这么高，然后表示理解。之后我们尝试过找泰国曼谷KAMOL医院骗他们说我已经20只是发育不良但是失败还被扣了2000押金，还找过泰国其他医生最后感觉泰国手术无望，便将希望寄托在国内的411赵烨德 九院刘阳 北医三院 最后锁定赵烨德也就是赵博

### 2022/12/26

> 我妈在网上联系赵后，赵和我妈说因为我情况特殊，可以向医院医务处申请，所以有一定希望可以做SRS，并且赵和我说如果医院同意，他很乐意帮助我，并建议我前往411面诊，因此，我们决定1月5日前往411找赵博面诊（都挂不到号是和赵商量加号的，不得不说，赵人是真的好，至少为了病人，他愿意加班，而不像有些医生快下班都不认真给人看病，并且我还不一定能做的了）

### 2023/1/11

> 我爸大老远从合肥开车带我去上海，去找赵，赵说他愿意帮我们但是要医务处同意，遂去找医务处，但是医务处就是不松口，因此，只能改变方案，一边尝试联系411,一边找上海九院的刘阳

### 2023/1/30
> 得知上海九院刘阳同意对我进行特殊情况下调年龄限制，但是由于要等待的时间很长，到时候我已开学，而且我已经休学两年在休学就要开除学籍，所以最后还是只能到安徽医科大学第二附属医院进行手术，这次一去就办好了住院
### 2023/2/1
> 医生检查后表示我因为本身就发育不良加上自切皮瓣不足不能直接造阴道而且因为体重超重无法进行腹股沟皮瓣移植或结肠移植(不要问为什么没有说腹膜)，所以医生的方案是通过扩张器两次手术完成 

### 2023/2/2
> 今天真是祸不单行的一天，医生告诉我安徽省卫健委不批这个srs手术，也就是完全没有希望做手术了，只能去上海九院了，实在不行只能想办法去国外了，回去的时候我爸车子还坏了回不去了

### 2023/2/9
> 我家在上海找到关系了！！！

**Comment by hunluan2** [comment]
关注后续，希望分享下赵博给的方案是零深度SRS，还是用其他材料替代制造阴道。

**Comment by LeeGuanLi** [comment]
好勇。。。真实年龄看一眼护照就知道了

**Comment by Cryolitia** [comment]
可重复性未知，MtF.wiki 无法鼓励该行为。
