### ISSUE TITLE
Kamol价格报告

### ISSUE THREAD

**Issue by sourceoflife123** [project-trans/MtF-wiki#703]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/srs/thailand/kamol/

### 内容

皮瓣 7万人民币
结肠（开腹）10.5万人民币
结肠（腹腔镜）12.5万人民币
腹膜 13.5万人民币
此为联系Kamol官网预留微信获得价格
还有Kamol定金是2000人民币
（本来想装成20岁手术结果失败告终，还被骗走了2000押金不退我）
顺便警告各位如果未成年去骗他们被发现了押金是不退的

**Comment by tuboshufps** [comment]
额有没有一种可能 你找的不是kamol医院 而是kamol的中介

**Comment by Neko-aLIEz** [comment]
感谢您的回报，我们这边也有可以获取 Kamol 价格的途径，真的很感谢您为此项目作出的贡献
