### ISSUE TITLE
上海市精神卫生中心-陆峥 极度不建议就诊

### ISSUE THREAD

**Issue by timi137137** [project-trans/MtF-wiki#709]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/psyco/shanghai/shmhc/

### 内容

近期收到非常多的人汇报说陆峥会让劝退等有一系列蜜汁操作，非常不建议去就诊，就算去了也会被四宫格打回。具体可以小蓝鸟搜索陆峥或询问身边人查证

**Comment by septs** [comment]
https://github.com/mtf-wiki/MtF-wiki/pull/705

CC @Cryolitia

**Comment by Cryolitia** [comment]
我上周刚去了，出诊一上午秒开，还是要看个人情况

**Comment by timi137137** [comment]
> 我上周刚去了，初诊一上午秒开，还是要看个人情况

如果是个例我也不至于开个issue专门提了，推特推荐都有几十个同一种情况的

**Comment by Cryolitia** [comment]
> > 我上周刚去了，初诊一上午秒开，还是要看个人情况
> 
> 如果是个例我也不至于开个issue专门提了，推特推荐都有几十个同一种情况的

「极度不建议就诊」等字样出现在wiki中是不恰当也是不准确的，四宫格等问题以及开证的充分条件已经在wiki页面写明，同时也注明了多条注意事项。如果有其他比现有页面更佳的表述，可以引导伙伴们更好的结合自身实际判断前往陆峥处就诊可能发生的情况以及利弊，欢迎在此条下继续交流。

以下是我的个人主观见解：
        看个人情况是指的，陆峥会比较严苛的评判就诊伙伴是否能够在进行变性手术后较为成功的在保守落后的社会中以女性身份正常生存。满足家庭支持或经济生活完全独立，评价较好的女性化外貌及女性装扮(及较好的女性声音)等条件一般是可以顺利的在陆峥处一次性开出诊断证明的。推特等社交平台同样存在一些初诊直接开证的反馈，我个人是上周在仅口头询问家庭是否支持，做了几个量表之后就初诊一上午就拿到了诊断证明。希望伙伴们可以结合自身情况选择更合适的医院就诊

**Comment by timi137137** [comment]
> > > 我上周刚去了，初诊一上午秒开，还是要看个人情况
> > 
> > 
> > 如果是个例我也不至于开个issue专门提了，推特推荐都有几十个同一种情况的
> 
> 「极度不建议就诊」等字样出现在wiki中是不恰当也是不准确的，四宫格等问题以及开证的充分条件已经在wiki页面写明，同时也注明了多条注意事项。如果有其他比现有页面更佳的表述，可以引导伙伴们更好的结合自身实际判断前往陆峥处就诊可能发生的情况以及利弊，欢迎在此条下继续交流。
> 
> 以下是我的个人主观见解： 看个人情况是指的，陆峥会比较严苛的评判就诊伙伴是否能够在进行变性手术后较为成功的在保守落后的社会中以女性身份正常生存。满足家庭支持或经济生活完全独立，评价较好的女性化外貌及女性装扮(及较好的女性声音)等条件一般是可以顺利的在陆峥处一次性开出诊断证明的。推特等社交平台同样存在一些初诊直接开证的反馈，我个人是上周在仅口头询问家庭是否支持，做了几个量表之后就初诊一上午就拿到了诊断证明。希望伙伴们可以结合自身情况选择更合适的医院就诊

你说的有道理，我个人见解是：
因为看见最近很多人因为JK/pass程度甚至只是抬杠就被打回，这里我道歉，是我用词过激。不过我希望能在wiki上提出不建议一些人去初诊，比如半家长党等，因为陆峥的话可能会让家长变成家暴党，这点希望能考虑一下。因为看wiki的不止成年了（有分辨能力）也有一些未成年人想带家长前往（我表达能力不太好，希望能懂吧）

**Comment by Cryolitia** [comment]
> > > > 我上周刚去了，初诊一上午秒开，还是要看个人情况
> > > 
> > > 
> > > 如果是个例我也不至于开个issue专门提了，推特推荐都有几十个同一种情况的
> > 
> > 
> > 「极度不建议就诊」等字样出现在wiki中是不恰当也是不准确的，四宫格等问题以及开证的充分条件已经在wiki页面写明，同时也注明了多条注意事项。如果有其他比现有页面更佳的表述，可以引导伙伴们更好的结合自身实际判断前往陆峥处就诊可能发生的情况以及利弊，欢迎在此条下继续交流。
> > 以下是我的个人主观见解： 看个人情况是指的，陆峥会比较严苛的评判就诊伙伴是否能够在进行变性手术后较为成功的在保守落后的社会中以女性身份正常生存。满足家庭支持或经济生活完全独立，评价较好的女性化外貌及女性装扮(及较好的女性声音)等条件一般是可以顺利的在陆峥处一次性开出诊断证明的。推特等社交平台同样存在一些初诊直接开证的反馈，我个人是上周在仅口头询问家庭是否支持，做了几个量表之后就初诊一上午就拿到了诊断证明。希望伙伴们可以结合自身情况选择更合适的医院就诊
> 
> 你说的有道理，我个人见解是： 因为看见最近很多人因为JK/pass程度甚至只是抬杠就被打回，这里我道歉，是我用词过激。不过我希望能在wiki上提出不建议一些人去初诊，比如半家长党等，因为陆峥的话可能会让家长变成家暴党，这点希望能考虑一下。因为看wiki的不止成年了（有分辨能力）也有一些未成年人想带家长前往（我表达能力不太好，希望能懂吧）

如果需要新增内容，需要讨论不建议就诊部分的具体内容及恰当性。你可以先写写试试然后提个PR

**Comment by septs** [comment]
引用部分已删除（提高信息密度），请勿“盖楼”

建议提交 PR 用以评估的你的变更部分时候合理（恰当）

**Comment by Cryolitia** [comment]
close with https://github.com/project-trans/MtF-wiki/commit/642c35993eb6c82e8c8b103c6de9ac2c24d1d74d
