### ISSUE TITLE
Kamol医院 极不建议找官网的中文中介 会吞定金

### ISSUE THREAD

**Issue by sourceoflife123** [project-trans/MtF-wiki#720]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/srs/thailand/kamol/

### 内容

>  本人因无法办理护照而无法前往泰国手术，但是他们说任何理由都不退钱给我，定金就这样被坑了，唉，就当钱给狗了吧

聊天记录及已付款证据：
![Screenshot_2023-01-16-20-28-17-426_com tencent mm](https://user-images.githubusercontent.com/119715532/212678973-0c4b825e-e079-4c46-9078-da71b49b9c6b.jpg)
![Screenshot_2023-01-16-20-25-57-011_com tencent mm](https://user-images.githubusercontent.com/119715532/212678980-96652914-9f1f-4d5e-b705-0ba68f5f31d7.jpg)
![Screenshot_2023-01-16-20-25-53-666_com tencent mm](https://user-images.githubusercontent.com/119715532/212678988-81fa56ba-f9f9-45dc-808b-490a694778c6.jpg)
![Screenshot_2023-01-16-20-25-13-213_com tencent mm](https://user-images.githubusercontent.com/119715532/212678993-fcb2fc66-cb01-41c2-ade4-c4b88a669b60.jpg)

黑中介微信 
![Screenshot_2023-01-16-20-28-38-592_com tencent mm](https://user-images.githubusercontent.com/119715532/212679100-c2326952-41b1-47fc-9160-1cc7b5c6458d.jpg)

**Comment by tuboshufps** [comment]
你对定金这两个字的理解是不是有什么误会…

**Comment by haig233** [comment]
定金本来就是拿不回来的，是你自己混淆了吧

定金给了你这属于爽约，谁会给你，除非你明确说明给的是订金，不是定金，订金返回是可以拿回的

**Comment by Neko-aLIEz** [comment]
看起来问题已经解决了，如果有需求欢迎随时 Re-open
