### ISSUE TITLE
建议在北三潘柏林、刘烨页面添加标注

### ISSUE THREAD

**Issue by tuboshufps** [project-trans/MtF-wiki#742]
建议 wiki editor 在相关页面添加注意及相关说明的标注

---

来源：https://twitter.com/fishmagic80/status/1623298490993369088

![](https://user-images.githubusercontent.com/3842474/219373736-477f34f7-f602-447e-a3b2-eaf8a6bd4819.png)

刘烨医生对寻求 HRT 指导的 MtF 给出“不建议使用激素” 的病历

---

来源：https://twitter.com/yayawaXi/status/1625307117635923968

![](https://user-images.githubusercontent.com/3842474/219373914-bf1a478f-f46a-4573-a631-2bbd29295427.png)

潘柏林医生对于 “有SRS计划” 的 MtF 给出 “建议考虑生育力保存，不建议注射类雌激素” 的病历

**Comment by septs** [comment]
希望不是孤例

**Comment by SoulGateKey** [comment]
来源一“刘烨医生对寻求HRT指导的MtF 给出“不建议使用激素” 的病历”中 引用的推文推主并不是MtF而是MtX

**Comment by zxgneil** [comment]
1. 刘烨医生作为内科医生比较谨慎，一般不给MtX或者非二元的跨儿提供激素治疗。如果有需求可以找潘柏林和常旭。
2. 潘柏林一般都会建议考虑保存生育力，特别是在有家长的情况下。如果已经和家里商量过了，可以明确告诉他和家里商量过了，明确不考虑生育力保存。北医三院的医生都不建议使用注射类的雌激素（比如日雌），会建议大家换成补佳乐或者凝胶。

**Comment by tuboshufps** [comment]
如果存在上述普遍现象，建议在相关界面进行提醒的的标注，或添加相关内容
（潘的建议保留生育能力…个人感觉是“不要做srs”的委婉说法

**Comment by saeziae** [comment]
是否认为标注以下两项比较合适？
1. 刘 标注不指导非二元性别者使用激素
2. 潘 标注会建议生育力留存

**Comment by tuboshufps** [comment]
> 是否认为标注以下两项比较合适？

是，但仍需更多案例佐证该说法。

**Comment by Clansty** [comment]
> 是否认为标注以下两项比较合适？
> 
> 1. 刘 标注不指导非二元性别者使用激素
> 2. 潘 标注会建议生育力留存

我觉得可行，可以在正文里补充案例，并且标注可能还有其他原因（？

**Comment by tuboshufps** [comment]
考虑到有家长陪诊的情况；如果刘、潘确实存在上述问题，且具有普遍性，个人会主动选择别的医生。
每位MtF的考量不一样，可以等待更多报告后添加标注，让读者自行判断是否前往。
对误导性的title致歉。

**Comment by FishMagic** [comment]
> 考虑到有家长陪诊的情况；如果刘、潘确实存在上述问题，且具有普遍性，个人会主动选择别的医生。 每位MtF的考量不一样，可以等待更多报告后添加标注，让读者自行判断是否前往。 对误导性的title致歉。

这里是第一张图中的当事人，被刘烨拒绝的主要原因是刘烨对非二元群体的激素使用缺少经验，且她认为我（或许包含整个非二元群体）使用激素的整体收益不高，因此拒绝提供处方，且出于审慎目的没有为我提供相关激素使用建议。她对MtF/FtM群体仍然会提供足够的帮助，无需为此担心

**Comment by Cryolitia** [comment]
> > 是否认为标注以下两项比较合适？
> 
> 是，但仍需更多案例佐证该说法。

根据多项独立报告基本可以确定刘烨会倾向于不建议MtX使用激素

**Comment by Cryolitia** [comment]
close with c5ae95373f8880b1ca6499597e34104cb7991755
