### ISSUE TITLE
北医三院新开的跨性别门诊

### ISSUE THREAD

**Issue by zxgneil** [project-trans/MtF-wiki#745]
### 医院名称

北京大学附属第三医院

### 医生姓名

常旭

### 标签

提供 HRT 指导, 需家长同意, 有检查项目

### 可开具的药品

戊酸雌二醇, 雌二醇水合物, 醋酸环丙孕酮, 螺内酯

### 注意事项

常旭医生在北医三院美容成形开了专门的跨性别门诊。时间是周一上午成形科（和潘柏林同一个入口）。

另外常旭在周五下午也会在成形科的普通门诊。普通门诊没有指定医生，所以需要在护士站分诊台指定需要看常旭医生。

有可以提供醋酸环丙孕酮，但是需要好大夫网站上线上问诊之后邮寄到家。

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Rinfair-CSP-A016** [comment]
如果可以，请仿照潘柏林/刘烨的wiki资料页提供该医生的有关具体信息，谢谢！

**Comment by Cryolitia** [comment]
我印象中北医三院跨性别医疗团队不止他三，还有心理科和整形科好几位医生，之前在公众号还是哪里看到过但是现在想不起来了，谁有可靠来源可以提供一下

**Comment by Cryolitia** [comment]
waiting for upstream
![image](https://github.com/project-trans/MtF-wiki/assets/23723294/08c7d80a-c55c-47d1-b350-0c59a601922a)

**Comment by Cryolitia** [comment]
Upstream updated：https://mp.weixin.qq.com/s/PjLOUen2EvWf5ZsusM-EvA

**Comment by Cryolitia** [comment]
这个可开具药品里的「雌二醇水合物」是什么东西

**Comment by Cryolitia** [comment]
因主要部分合并入主线关闭，「雌二醇水合物」问题留待进一步讨论
