### ISSUE TITLE
董燕（临汾市中心医院）

### ISSUE THREAD

**Issue by bilibiliXiaoLu** [project-trans/MtF-wiki#748]
### 医院名称

临汾市中心医院（解放院区）

### 医生姓名

董燕

### 标签

需家长同意

### 可开具的药品

戊酸雌二醇, 醋酸环丙孕酮, 螺内酯

### 注意事项

问诊细节：

1. 第一部分：自述从（幼儿园、）小学、初中、高中、大学到现在关于性别焦虑的经历，觉醒的时间和原因
2. 第二部分：家长是否知情理解
3. 第三部分：来这里希望寻求什么帮助

注意事项

1. 是解放院区不是平阳院区（半秋因没发现此医院有临床心理科去了精卫被要求住院了）
2. 医院处方在取药后会收回，记得提前拍照或医生手写处方

总结：可能需要多次就诊。

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Rinfair-CSP-A016** [comment]
你好~以防万一再次确认一下，这个医生是 心理科开具易性症诊断证明 还是 内分泌科给持证mtf开药 的。。？

**Comment by Leetfs** [comment]
因时间略久，无法联系到本人求证。

查证发现`董燕`为临汾市中心医院临床心理科医师，该医院为综合三甲医院，结合问诊细节和注意事项，合理推测作者是在心理科开的处方然后去内分泌科开药）
https://linfench.com/?p=expertshow&lanmu=13&id=16&sid=285

或许可以考虑仅将精神科就诊部分同步到wiki
