### ISSUE TITLE
在“通俗用语表”添加“小证”“大证”“假条”是什么及其区别

### ISSUE THREAD

**Issue by wmtdru8xip** [project-trans/MtF-wiki#749]
在 实用信息 通俗用语表 解释“小证”“大证”是什么及其区别

**Comment by septs** [comment]
基于目前已知的信息来说，“大证”是指能够用于在中国大陆进行 SRS 的诊断证明，“小证”亦之 （一般用于简化沟通）

**Comment by SoulGateKey** [comment]
小证不应该是门诊病历么

**Comment by wmtdru8xip** [comment]
还有“假条”？

**Comment by septs** [comment]
> 还有“假条”？

目前开具“假条”并应用于 HRT 的仅 北医三院 与 回龙观，我认为并不是普遍化的

**Comment by ddzzkunye** [comment]
所以什么是小证?

**Comment by Cryolitia** [comment]
> 所以什么是小证?

https://github.com/project-trans/MtF-wiki/blob/fd5dcce3f9f5fc969a1b6c069cf689253c629264/content/zh-cn/docs/psyco/psyco-overview.md?plain=1#L69
