### ISSUE TITLE
zh-CN / zh-hant 傻傻分不清楚，建议添加专门的说明文件

### ISSUE THREAD

**Issue by Misaka-0x447f** [project-trans/MtF-wiki#754]
如果是 zh-hans 和 zh-hant 可能还能分得开，现在这样就完全分不清了
可以的话找个适当的位置塞 readme 吧，可以是这两个语言文件夹下，也可以是贡献指南之类的

**Comment by septs** [comment]
Related issues: #69

**Comment by saeziae** [comment]
Duplicated: #69
歷史遺留問題，一個是因爲既有分享鏈接與 SEO，另一個是因爲確實 zh-cn 是 china centric 的，如果可以的話做重定向就行。

**Comment by saeziae** [comment]
因短期内无法就此问题做更改，故关闭。

**Comment by Cryolitia** [comment]
尊敬的贡献者您好，我们在近期启动了《MtF.wiki 站点国际化设计提案》的起草与表决工作，您可以前往 https://github.com/project-trans/summit/pull/1 参与讨论，感谢您对 MtF.wiki 的关注与支持！
