### ISSUE TITLE
成都市第四人民医院（九江院区）- 戴静

### ISSUE THREAD

**Issue by tonori** [project-trans/MtF-wiki#757]
### 医院名称

成都市第四人民医院（九江院区）

### 医生姓名

戴静

### 标签

初诊获得证明/假条

### 注意事项

1. 本人已满 18 岁
2. 戴静医生出诊时间和诊室为 **周一下午，特需医疗（情绪）门诊**，挂号费 300 元，推荐提前一周挂号，当日要求加号的话会等到很晚。

### 补充

以前就是戴静医生的患者，以 **出入境需要审查病历资料** 为由询问是否可以开出 `易性症` 或 `性别焦虑` 诊断。戴静医生次日查询门诊系统后回复：“可以开出 `易性症` 诊断”。
> 印象中曾经有过成都市第四人民医院可以开证的报告，但从戴静医生的行为感觉，戴静医生也是第一次开相关诊断。
> 使用戴静医生的诊断在四院其他科室就诊时，曾就诊过心神医学和睡眠科室的三位医生均认可戴静医生的诊断。

![IMG_8525](https://user-images.githubusercontent.com/47135403/222086605-a5c021db-5216-4247-9096-66f15692c2b6.PNG)

### 证明样式

![Xnip2023-03-01_16-37-15](https://user-images.githubusercontent.com/47135403/222086969-2fe5e653-15aa-4acb-8f93-585af6a32dea.jpg)

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Rinfair-CSP-A016** [comment]
首先，感谢提供信息！
其次翎澈有些内容想和你确认或者是希望你补充！

1.戴静医生只出诊这一个院区/科室/时间段吗？如果不是，你能否补充一下？
2.如果不以这种理由去开诊断而是作为普通患者（以HRT为目标）去开诊断，会有什么问诊流程？是否需要家长陪同？需要做哪些检查？
3.你是否能根据wiki上其他医生的记录格式补充一些其他的相关信息？

最后再次感谢你提供以上资料！

**Comment by tonori** [comment]
1. 戴静医生只在这一个时间段出诊
2. 其他目的的诊疗流程尚不明确，希望能有更多的就诊反馈
3. 我对比了 wiki 上其他医生的记录格式，我的 issue 里应该就是缺少 `问诊过程` 的有关描述。如果还有其他希望补充的点可否指出？

> 周二会出心理咨询（同样在四院），其他时间段可以以 **心理咨询**  名义在院外约到戴静医生。
> 但是我认为心理咨询对开诊断没有什么帮助作用，在院外约戴静医生的价格比院内还要贵几百。

**Comment by Rinfair-CSP-A016** [comment]
目前没有了，感谢你提供的资料！

**Comment by Leetfs** [comment]
查询发现该医生仍出诊，且wiki上缺失相关信息，这两天我整理一下
