### ISSUE TITLE
关于《家长知情同意公证书》在411赵博处效力的反馈

### ISSUE THREAD

**Issue by cocoAutumn** [project-trans/MtF-wiki#772]
其他实际影响手术实施因素：

- 家长对院方的骚扰
- 医生的主观意见

本人情况：

> 2021年7月于北大六院唐宏宇处取得假条，2022年2月于唐处取得诊断证明，同时在北医三院开始HRT随访并于6月进行了染色体检查，累计开具处方三次。
>
> 2022年2月进行了关于SRS的本人申请公证，2月和4月分别进行了两位家长的知情同意公证（均在北京进行）。
>
> 2022年8月于411赵博处首次面诊（出示了上述全部纸质材料）并取得了2023年3月的SRS排期，2023年3月再次独自面诊时赵博以「与我父亲通过电话得知有外地的心理医生告知我父亲易性症可经由非暴力的心理治疗成功矫正」为由与我母亲通了视频电话，随后甚至无法对我给出精确到周的入院日期而是将我推荐到了上海精卫的一位无开证资质的医生处。
>
> 次周我与父母共同找该医生面诊后又一同面见了赵博，赵博明确向我单独表示「即使持有双亲的《知情同意公证书》并带来面诊」（因而也显然满足了2022年SRS标准中的“知情”）依然不能无视他们的当面（或电话中）口头反悔，且会导致入院无限期推迟。

是否个例有待补充。

**Comment by Rinfair-CSP-A016** [comment]
@cocoAutumn 若公证流程正规且公证书具有法律效力，反悔理应是无效的，此内容有待进一步观察

**Comment by tuboshufps** [comment]
这不是个例，赵博更注重父母当下的意见。即父母同意手术。
可以理解成“加码”

**Comment by cocoAutumn** [comment]
确认是“加码”了，赵博对这种“只差临门一脚”的准家长党的当面宣教作用真的非常好（插句题外话，疫情以来他们团队面向mtf的srs技术有突破性进展）。
不过对于真的家长签过字又明确反悔的小伙伴来说需要引起注意（毕竟如果真的有纠纷，全院的srs资质都可能被停掉的），为避免恐慌，建议工作组拟好赵博wiki页面的修改内容后（好像本身就挺过时了还有疫情相关内容）就尽快关闭本issue。

**Comment by saeziae** [comment]
此issue建议开放讨论，可考虑将链接放到wiki对应界面。

**Comment by cocoAutumn** [comment]
情况更新：使用不来自家长的资金作为入院押金（5W），入院后疑似有“无法安排术期”现象？（体现为比自己入院更早和更晚的姐妹被安排在了同一周而自己在入院72小时后的工作日仍被亲口告知尚未安排，但前期检查项目都做了）

**Comment by Rinfair-CSP-A016** [comment]
@cocoAutumn 你能否确认原因？（例如前期检查出现异常之类的）

**Comment by cocoAutumn** [comment]
胸片、心电图、彩超等现场检查项目如有异常会直接口头告知（本人没有），抽血和大小便化验不明……

**Comment by shiawasenahikari** [comment]
我与当事人是男女朋友关系
当事人于 2023 年 3 月 28 日，和其父母再次面诊赵博时，当事人的父母当时表示同意当事人入院接受 SRS 服务
赵博当时令当事人于"下周一或周二"，即 2023 年 4 月 3 日或 4 日办理入院手续，我带着当事人于 4 日下午现场办理了入院手续，并支付了 5 万元人民币押金。以下是中国工商银行 app 的该笔账单截图
![Screenshot_20230408_201008](https://user-images.githubusercontent.com/32567875/230720311-9fe1cd5f-967a-45a4-8a82-8111f5c489d6.jpg)
当事人的术前体检均已进行完毕，但却出现了"同时有入院早于及晚于当事人的姐妹已确定术期，当事人却仍未被安排术期"的情况。
当事人入院后，其微信仍然每天被其家长轰炸，本人合理怀疑当事人的手术延期与其家长幕后的口头阻挠相关。

**Comment by shiawasenahikari** [comment]
我与当事人是男女朋友关系
当事人于 2023 年 3 月 28 日，和其父母再次面诊赵博时，当事人的父母当时表示同意当事人入院接受 SRS 服务
赵博当时令当事人于"下周一或周二"，即 2023 年 4 月 3 日或 4 日办理入院手续，我带着当事人于 4 日下午现场办理了入院手续，并支付了 5 万元人民币押金。以下是中国工商银行 app 的该笔账单截图
![Screenshot_20230408_201008](https://user-images.githubusercontent.com/32567875/230720311-9fe1cd5f-967a-45a4-8a82-8111f5c489d6.jpg)
当事人的术前体检均已进行完毕，但却出现了"同时有入院早于及晚于当事人的姐妹已确定术期，当事人却仍未被安排术期"的情况。
当事人入院后，其微信仍然每天被其家长轰炸，本人合理怀疑当事人的手术延期与其家长幕后的口头阻挠相关。

**Comment by shiawasenahikari** [comment]
如果对于这家医院来说，那么多的术前证明材料都没有一句家长的口头阻挠更有法律效力的话

那我只能强烈建议非家长党的姐妹不要选择这家医院

**Comment by Cryolitia** [comment]
这种事情需要更多证据和关联报告，而不仅仅是推测。以普遍理性而论，411长期存在床位紧张的情况，不太可能出现一直占着床位不安排手术的情况，建议进一步核实原因，关注各项检查结果有无异常或需要复核的。

另一方面，确实需要考虑家长实时的意愿在411的效力，之前有过携带同意公证书但是父母口头否认，被拒绝安排手术的报告。

**Comment by shiawasenahikari** [comment]
涉及敏感信息，故脱敏处理后重 po
我与当事人是男女朋友关系
当事人于 2023 年 3 月 28 日，和其父母再次面诊赵博时，当事人的父母当时表示同意当事人入院接受 SRS 服务
赵博当时令当事人于"下周一或周二"，即 2023 年 4 月 3 日或 4 日办理入院手续，我带着当事人于 4 日下午现场办理了入院手续，并支付了 5 万元人民币押金。以下是中国工商银行 app 的该笔账单截图
![Screenshot_20230408_200850_com icbc](https://user-images.githubusercontent.com/32567875/230722556-7ac15ee9-2750-412d-8bf4-c8a770607258.jpg)
当事人的术前体检均已进行完毕，但却出现了"同时有入院早于及晚于当事人的姐妹已确定术期，当事人却仍未被安排术期"的情况。
当事人入院后，其微信仍然每天被其家长轰炸，本人合理怀疑当事人的手术延期与其家长幕后的口头阻挠相关。

**Comment by cocoAutumn** [comment]
> 情况更新：使用不来自家长的资金作为入院押金（5W），入院后疑似有“无法安排术期”现象？（体现为比自己入院更早和更晚的姐妹被安排在了同一周而自己在入院72小时后的工作日仍被亲口告知尚未安排，但前期检查项目都做了）
情况再次更新：入院满168小时，被安排在了入院240小时后手术，属于正常范围。

**Comment by cocoAutumn** [comment]
<details><summary>另一案例</summary>

![2af9df1f6d7bcfb3](https://github.com/project-trans/MtF-wiki/assets/88474935/d01da4e7-ce5e-46b9-890d-bbf668254124)
</details>
