### ISSUE TITLE
激素换算 增加IU单位

### ISSUE THREAD

**Issue by Cryolitia** [project-trans/MtF-wiki#773]
[国际单位 - 维基百科](https://zh.wikipedia.org/zh-hans/%E5%9B%BD%E9%99%85%E5%8D%95%E4%BD%8D)

部分医院使用IU作为泌乳素激素检查结果的单位

**Comment by septs** [comment]
可使用 https://transfemscience.org/misc/hormone-conc-unit-conv/ 进行替代

**Comment by Cryolitia** [comment]
强烈谴责直接摆烂的行为

**Comment by Rinfair-CSP-A016** [comment]
yysy，transfemscience也没有IU单位。（很明显这不是个特别通用的单位，而且我们对其换算法也不是很清楚）

**Comment by Cryolitia** [comment]
> yysy，transfemscience也没有IU单位。（很明显这不是个特别通用的单位，而且我们对其换算法也不是很清楚）

https://en.m.wikipedia.org/wiki/Prolactin

这上面有说，标准是IS 84/500，mIU到μg是除以21.2

**Comment by Cryolitia** [comment]
> 有没有例子，哪家医院的泌乳素是IU单位？

- 山东省立医院

待补充

**Comment by Rinfair-CSP-A016** [comment]
Completed due to #777.
However this topic will remain open for future use.

**Comment by Cryolitia** [comment]
close due to no meaning

> 哪来的谜语人，`feature use`是什么
