### ISSUE TITLE
在 SRS / 手术技术 / 腹膜 栏目增加 Dr. Heidi Wittenberg

### ISSUE THREAD

**Issue by fInnOcentsh** [project-trans/MtF-wiki#782]
根据[一篇博客](https://drzphd.com/trans-feminine-blog-1/peritoneal-pull-through-vaginoplasty-what-do-we-know)中所述，美国的 Dr. Heidi Wittenberg 也已可以进行腹膜手术，原作者自述已经电话沟通确认，而 Mosaic Care 网站的[介绍页面](https://www.mozaiccare.net/mtf-surgery)也列出确认了执行这项手术的能力。

**Comment by Leetfs** [comment]
MtF.wiki 内已有相关信息

https://github.com/project-trans/MtF-wiki/pull/382

**Comment by Leetfs** [comment]
感谢贡献，刚才看错了。
