### ISSUE TITLE
”京医通“停止运营

### ISSUE THREAD

**Issue by EL-File4138** [project-trans/MtF-wiki#786]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/psyco/beijing/bhlgh/#register

### 内容

因运营问题，”京医通“微信公众号挂号服务将于4月24日0时起停止运营。建议删除相关页面的过时挂号指引。

Src：[北京日报](https://mp.weixin.qq.com/s/VlUTQ7zUkU7_6SvUpDbw2g)

**Comment by Rinfair-CSP-A016** [comment]
@EL-File4138 此内容已纳入修改计划，北京方面的全部资料将在京医通停止运营时同步更新
