### ISSUE TITLE
后疫情时代 MtF 在 411 进行 SRS 流程参考

### ISSUE THREAD

**Issue by cocoAutumn** [project-trans/MtF-wiki#789]
https://github.com/project-trans/MtF-wiki/issues/694 撰写于2022年末，与2023年的后疫情时代情况有一些出入，因此本文将尝试重新整理现在的情况。

## Sec1. 入院

> 当前赵烨德处 SRS 手术排期较长（截至2023年4月排期已需要一年），预约需要一定心理准备。

上面的引用内容表明，411 的排期比起北医三院（在资质材料准备充分的情况下）似乎也失去了优势。然而疫情以来 411 依然是国内 MtF 的 SRS 领头羊，至少不会像泰国一样时不时出个事故……

我是在 2022 年 8 月中旬初次前来 411 面诊排期到 2023 年 3 月的，实际由于忙于毕设，再次面诊于 3 月下旬进行。微信公众号的预约挂号提前量很长（一个月），可以及早安排并与赵博保持微信联系，万一挂不上那就礼拜四早上在门诊部找整形外科的白帽护士现场加号吧，或者在礼节范围内在住院部找赵博面谈。

关于“手术前需要停止 HRT 一个月”，北医三院的刘烨医生称“未去势的只停雌不停抗雄即可”（基于血栓风险），411另一已去势数年的医学生病友反馈“针剂HRT者应停用两个月”，实际将根据入院后激素六项化验中的双促水平来判定停药时长。

https://github.com/project-trans/MtF-wiki/issues/772 的反馈表明，如果这次面诊前一个季度内家长向赵博表现出犹豫和反悔的态度，就会需要额外的面谈宣教工作，如果觉得自己的家长比较冥顽不化，请保管好护照等证件做两手准备……

入院当天（工作日都可），门诊部整形外科的白帽护士会让你挂一个门诊号，然后陈医生会收走你的以下材料：

（无需婚姻相关证明，因为确实有患者在境外与证件同性者结婚的先例，这点比北医三院好 n 倍）

1. 易性症诊断证明
2. SRS 的本人知情同意公证书
3. SRS 的父母知情同意书（我交的是公证书）
4. (可选?)无犯罪记录证明（赵博称半年内有效，不少省份可以线上自助开具后自行打印）

然后就会给你一个要带去住院部一楼缴费的单子（一般是5万元），当天有效。

这是你最后可以亲自在上海市实体店采买各种物品的机会，入院以后再要穿便服出门就要请假了，外卖配送费可不便宜而且还需要有人下楼去取不是吗。

物品清单：

1. 插线板+小风扇，前者几乎是必须的，你要充电的设备至少也包括手机和小风扇这两个吧。小风扇（注意充电方式）不光用于拆包后吹阴部还要用于术后解暑，毕竟躺平不能翻身的话气温稍高就会满背汗，默认的厚枕头也容易搞得满头汗，不玩手机的时候跟护工阿姨要个薄枕头吧。吹风机倒是没必要，即便术前也无需每天都洗头，护工阿姨会借你的。
2. 牙刷牙膏+脸盆毛巾肥皂+碗筷勺，筷子用于食用铁盘盛装的午晚普食，碗勺用于早餐粥（也许术前你用不到勺子但术后第二周恢复进食以后就要用到了）或午晚汤（可选），其他用于术后护工阿姨对你的清洁工作（肥皂用于每天清洗毛巾，但也可用沐浴露代替）。关于漱口杯，清晨卧床刷牙实际需要一个饮水杯和一个吐水杯，因为太麻烦了建议只准备一个，另一个用一次性纸杯+一次性弯吸管代替。牙刷未必需要电动的（没电了岂不是更尴尬），如果你左手卧位刷牙足够熟练的话。
3. 带吸管的饮水杯，考虑到吸管深度，实际能一次连续饮用的水量是要低于杯子容量的，但也没必要非得像某些姐妹一样弄个一升起步的大壶？
4. 梳子+两个不易断的橡皮筋，术后每天护工阿姨会给你梳麻花辫的双马尾（睡觉也不解开），即便如此一周后你的头发甚至病号服上衣依然会变得像手术当天呕吐的胆汁一样酸臭qwq
6. 小手电筒+手掌大的矩形小镜子，用于拆包后自行观察阴部并通模具/用药，最好不要想着用手机代替其中任何一个……
7. 消耗品如无酒精湿巾（80张每包）+抽纸（大约半提）+洗发水+沐浴露（这两个用100g以下的小包装），湿巾用于擦汗+大便后擦屁股。
8. 药品，草木犀流浸液片2盒，迈之灵片1盒，康瑞保祛疤凝胶，布洛芬，蒙脱石散成人款，各有各的用处。
9. 安全套+红霉素软膏+日用卫生巾+全棉紧内裤（数量足够换洗），拆包后通模具以及出院后使用。
10. 懒人加长手机支架，术后第一周单手操作手机必备，第二周起横屏长时间播放视频或闭目听歌也很有用。耳机不一定非要无线的，因为有线的可以线控调节音量/切歌，而且手机充电速度/续航够好的话并不会很冲突。
11. 拖鞋，但是入院时床下往往会有前任留下的，如果自己的鞋本身很容易不用手就穿脱也可以不需要。
12. 中单（床上一次性护理垫），医院附近的药店就能买的到，一提应该足够。换药时会纵向铺在臀下，平时考虑到意外大便频率最好对折后再铺这样能用两次，术后第一周不会大便的情况下护工阿姨可能会用病号裤代替来改善触感。
13. 粗网灭菌凡士林纱布25×40cm，10片128元包邮买一份就够（但是似乎只有淘宝有，平时只用微信不用支付宝的小伙伴提前注意），评论区会有 MtF 告诉你的。\
参考链接：https://detail.tmall.com/item.htm?id=582921441062

住院部一楼缴费后要妥善保管押金单，此时你卡上最好还要有1万元左右的余额用于覆盖下列费用：

1. 新的液态止血涂料来填充皮瓣与造口间的空隙，1554×4=6216元，可以手术当天早上找赵博让他给你一个支付宝收款码来扫。
2. 护工费用100元每天，从手术当天起算，一般至少要到拔尿管那天。
3. 抗血栓弹力袜688元，自行提前购买往往会便宜没好货。
4. 其他零七碎八的外卖/网购费用，出院后的公证费、路费、行李快递费……

到达病区后，先会在护士站了解一些注意事项并签字领取病号服+腕带+两卷纱布，然后去病房整理行李吧。我是把一双鞋+脸盆，毛巾+牙刷牙膏+碗筷勺放在床下的架子上，床头柜上只放插线板+水杯+抽纸等。

当天的午饭和晚饭就已经需要你用筷子来吃了，菜汤需要碗来盛不过我没有这样的习惯（后果是便秘但这在术后第二周恢复进食以后反而是好事），吃饱了以后把剩菜剩饭丢弃在走廊尽头的泔水桶再去电梯间的开水房把餐盘稍微用水冲冲就放在水龙头旁边吧。

关于两卷纱布的拆解，你需要在护士站借一把剪刀把它剪成正方形小块（通过对折减少剪的次数），然后从对角线出发撕成一条条线，装在一个塑料袋里，最后交给护士站她们会拿去消毒。

医院的作息确保你只要入院和手术不在同一周就一定有空搞完这项工作，不过揪对角线的手指会磨得比较不舒服。

关于三餐，分别在06:50、11:00、16:50，早餐是半流食=一个蒸煮鸡蛋（军训过的都知道怎么去壳吧）+一个馒头/包子+稻/粟/黑米粥（建议不要咸菜），午餐和晚餐的普食都是米饭+青菜+一荤+一谜（一荤可能是带刺的鱼，一谜可能是鸡蛋），半流食则是馄饨（馄饨汤有点咸，这是因为术后第二周不会再滴生理盐水）。
一天共22元，能吃惯的话还是很省钱的。

作息方面，春分到秋分之间上海早上6点已经天大亮了，大夜班护士是早上8点交班，非过夜陪护的家属需要在晚9点前离开（晚9点后通向电梯间的门会锁上，如需去开水房要提前去），过夜陪护仅限1人（10元每晚）且早上6点以后就没地方睡了。

病友方面，最常见的是几天一换人（换人会拉上帘子用紫外线灯消毒不要直视）的小手术 FtM（大部分年龄有30+且可能有文身），他们的手术从胸部的“大切、环切、微创、乳头修复”到下体的“一期（两切除一闭合）、二期（尿道提升加皮管）、三期（硬化或勃起器植入）、四期（镶两个假蛋蛋？）”而不像我们一个词“反方向”概括了事，FtM 有很文静的小正太也有互相串门聊得热火朝天去开水房抽卷烟甚至在病房抽电子烟的，如果你术前他们对你太热情你不喜欢那就装聋作哑去别的病房找姐妹玩吧。如果同病房有幸有 MtF，那也要小心是不是比较公主病扰民的那种，扰民可以找护士站投诉哦。

FtM 的 cisF 家属有可能会找你交流胸部的发育问题和后续的隆乳打算，~~可以试着提出观察对方的下体作为交换条件~~我只敢互相脱上衣看看。

入院最迟第二晚会给你大小便标本盒和几个检查单，分别是胸片、心电图、内脏（空腹）和睾丸彩超（彩超可能要次日8点到护士站才会告诉你到底约到了哪个时间段），并且会要求你晚饭后禁食禁水次日6点会来采血（闭着眼躺好吧，内容应该有血常规、血型、激素六项、艾梅乙丙、生化凝血等等）。

次日抽了血打了早饭千万不要像我嘴欠把馒头/包子吃了，而是先全部放回床头柜然后去采集大小便标本并按要求提交（便秘哭哭）。
临近8点时去3楼心电图室把单子交给检查员排上号码，再去1楼拍胸片（很快）或去护士站询问如果彩超不在当天那就可以把早饭吃了，然后估摸着时间去做心电图吧。

管床医生会在合适的时机（我是入院当天）把你叫去办公室讲解术式原理（家属在的话可以听一听但是看图片就太吓人了），会再签一些字并且测量腿围付款订购弹力袜，然后去病房检查你的下体材料是否足够，不够的（如割过包皮甚至切除过性腺）要另外商量手术方案比如从腹股沟甚至腰侧取植皮。

术前一天早饭建议不要吃馒头或包子（只吃鸡蛋和粥），午饭也别吃。午后麻醉医生会来病房找你签最后一组字（重点是“同意全麻，同意镇痛”），然后护士站会检查你的手指甲长度（1毫米足够你在出院以后去美甲店涂色不会涂到皮肤上了，脚趾甲自行检查），给你2支开塞露和24组舒泰清（明明是4盒各6组但是非要分3次各8组喝完）和一个750mL的大纸杯，收走你的凡士林纱布。

你要在15、17、19点各用温开水在十分钟内喝完一杯，前两组之间护士会来给你备皮（刮毛毛），第二杯喝完时可能就会有催吐感了这时候去坐在马桶上吧，稍微拉舒服了以后好好洗一个澡（重点是上肢以外，南方小伙伴务必用澡巾把背腰臀腿好好搓搓，术后可是两周不能翻身的）。

第三杯你可能会呕吐掉一大半，但是如果清肠清不干净的话第二天在手术台上拉出来了那就只能仅做性腺切除了（为了避免这种情况，容易便秘的小伙伴建议术前倒数第二天就不要吃零嘴和外卖了）。20点会有护士来用生理盐水灌肠，再去拉干净以后就要躺下输一会液了（21点后禁水）。

## Sec2. 手术

设手术当天为d+0。早上六点半让护工阿姨给你把两只开塞露用掉，稍微憋一下下就去拉干净吧，八点赵博带人查房时会确认你的决心，然后护士站给你量完血压以后你就回去把新的病号服和弹力袜穿好（其他什么都不穿，鞋子在手术区总入口让护士或家属拎回来），等待叫到你时你小便一下就一起去手术室楼层了（没有肌注针，无需携带安全套，里面室温比较低）。躺在手术台后会先开始输液，然后扣上氧气面罩以后你会慢慢有昏睡感，不要抗拒，闭上眼静候新生……

在手术区的复苏室苏醒后，就会把你推回病房了（室温骤升），48小时共96mL的止痛泵开始运作，你的痛感主要会来自精索和海绵体（真就是幻肢痛呗），其次是肛周的引流管切口。不建议学习某些病友白天把止痛泵关掉来延长使用天数，因为d+3夜似乎还可以争取到一支止痛针（吗啡/杜冷丁）。

d+0回到病房后你会在不输液的那只胳膊上绑好血压计每小时测量（胸口贴几个片做心电监测直到次日清晨），去枕平卧并吸氧（刻意憋气半分钟以上会有蜂鸣器提醒你继续呼吸），期间你会各种呕吐深绿色的胆汁（需要护工阿姨在一侧准备好塑料袋并垫好卫生纸），很不好受。
当夜8点或更早输液结束时告诉护士你要打止痛针，9点就会来给你打了。
我是分别在d+0、d+2、d+3各打了一次（d+3护士请示了上级），因为躺久了一直不排气的话，腰背和内脏（肚脐以上肋骨以下）会比下体更疼。止痛针会打在盆骨下面的臀肉上，如果有出血会用棉签压一小会，然后你的整个腹腔和大脑会有“低电压自动关机”一样的感觉，闭上眼很快就能入睡……

d+1开始就可以枕枕头+用手机支架单手操作了，白天请务必用好音乐（未必是视频，因为你不一定睁得开眼）来辅助镇痛。

换药在d+3（含拔引流管）、d+6、d+9、d+11，拆包下地在d+12，拆线拔尿管在d+14。
止痛泵和止痛针都用完以后如果还疼或者有发热，就得在晚间输液结束后（比如20点）吃自己买的布洛芬了，但是禁食期间空腹吃这个容易烧心，可能需要先喝不少水。

术后第一周禁食并可以吸氧（但没必要一天吸十几个小时），每天会有十余袋输液，涵盖葡萄糖、生理盐水、消炎等，其中有一小袋用氯化钠配的药滴注速度快了血管会痛记得让护工阿姨调慢。输液用的是留置针，但不建议一整周都用同一只手，会出问题的。

第一次换药结束后差不多该排气了，但每天不要喝太多水（第二周起饮食同理）否则放屁容易带出大便（危），万一在第二次换药前发生这种情况，就必须把臀下垫着的病号裤换成不太舒服的中单了，而且护工阿姨会给你弄个便盆让你稍微多喝一点水尽量一次拉干净（很硌屁股，拉了好多黑糊糊），或许需要配合服用蒙脱石散成人款。

411在4月是不会开空调的，但是开窗户的话地铁运营等声音会持续到23点多，白天闷热的情况下背部极易满汗（头颈部在夜间也是，有需要请让护工阿姨弄个薄枕头），务必用小风扇多吹吹（注意充电，但不要吹到打喷嚏甚至发热，每天会测很多次体温需要自己数5分钟记下数值因为护士不会报给你），并配合调整被子在支被架上的位置来达到双腿通风或露出上半身的效果。脚踝以下切忌长时间不动，玩手机之余记得时不时纵向旋转脚板和脚趾。

## Sec3. 

等有待5月初更新……欢迎插楼讨论

**Comment by Frozenyousa** [comment]
嗷呜——

**Comment by cocoAutumn** [comment]
## Sec3. 康复
首先是之前内容的修正和补充：
1. 绑麻花辫的双马尾需要4个不易断的橡皮筋而不是2个。
2. 手电筒是用不到的，小镜子在出院后往往也可用手机前摄代替。
3. 本人没有用到布洛芬和感冒药以外的口服药（康瑞保祛疤凝胶出院后才会用到），看来是肠胃太好了。
4. 全棉紧内裤在出院前只需要一条，因为垫了卫生巾是不可能弄脏的。卫生巾的尺寸以245到275mm纯棉日用为宜，180mm的迷你型很可能是黑心棉，如果渗液很严重则可能会需要夜用。
5. 安全套在出院前只需要几个，赵博声称红霉素软膏可能和安全套的乳胶或聚氨酯材质或其添加剂（比如香料、色素或自带的少量润滑剂）发生反应引起某些个体不适，但我因为劳动节假期的缘故并没有领到普朗特凝胶。
6. 中单在臀下铺久了容易粘在屁股上，在不会渗液或漏粪的情况下可以在上面多垫一个毛巾。
7. 模具方面，我的阴道设计尺寸是12×6（材料不够的可能就只有10×5了），因此2.5的硅胶模具还是很轻松的，不过作为情趣用品而不是医疗器械的模具在尺寸跨度上并不像泰国的玻璃模具那么密集，而是跨度比较大，2.5下一个直接就是3.0了，计划出院一个月后尝试。
8. 入院5个W最后退了两千多，护工费用累计用了21天，还有一个150元的气垫床，另外陪护过夜每夜10元的费用是出院时另外支付的并不会从入院押金里扣除，护工阿姨替你垫付以后会把发票给你。

在第二周吃几天流食以后就会恢复普食了（也差不多该脱掉不舒服的弹力袜了），吃的时候护工阿姨会帮你把床摇起来一定角度，尽管如此还是建议普食由一位陪护（未必要过夜）从铁盘转移到饭盒里你再端着吃，直接端铁盘会很麻烦的，如果你根本吃不惯并且财大气粗那就叫外卖吧。

清洁方面，从d+1开始，每天早上6点半左右护工阿姨会帮助你刷牙（是的，只刷早上一次），然后是用毛巾擦洗脸、脖子和双手（包括小臂，但留置针的手掌只擦到手指，没有留置针的话会把毛巾递给你自己先双手擦擦脸和脖子），晚间也有一次擦洗并且在第二周（尤其是恢复普食之后）会包括擦腿脚以及侧翻90°来擦背部。但是要注意擦脚用的是擦脸的同一条毛巾，虽然躺那么久的你脚肯定比手干净但如果有脚癣什么的请务必告知。拆包以后尤其是拔尿管以后，还会用湿的棉球和棉签擦洗伤口（有一些痂会自然掉落）。

关于排便，恢复饮食尤其是普食以后，可以借助饮水和水果将大便控制在既不至于窜稀又不至于便秘的程度，然后就可以在合适的时候呼叫护工阿姨拿个小盆垫在臀下开拉了，拉完了再叫她帮你擦干净（需要用到卫生纸和不少湿巾）。

拔尿管前一两天要练习憋尿，方法是把尿管上的夹子夹住然后多喝水，快憋不住了再放开。可以听到尿液哗啦啦地进入尿袋，并且快流完的时候膀胱会被刺激几下要做好心理准备。还要练习下地站立和在房间内行走（直到能走去洗手间大便甚至被护工阿姨洗头），因为不像兄弟们可以坐直而只能是躺着和站着两个极端，因此前几次下地会非常痛苦，双脚着地以后即便不移动也会在半分钟内失去听觉甚至视觉（大脑血氧不足），就需要再躺下缓缓，一天练习几次，最后就可以走去换药室拆线拔尿管啦。

出院时，准备好甜甜圈坐垫，护工阿姨会把你送上你自己叫来的网约车，前往几公里远的上海市东方公证处，公证事项是那张《诊断证明书》的【影印件与原件相符，原件属实】，建议要三份副本，另外公证处还需要复印你的【户口簿（集体户口就是首页的盖章复印件以及自己那一页）、身份证、出院的病历、三甲证明、绿色的简明账单等】，公证书建议邮寄（很快的，不到半周），但要务必保管好那张《公证受理通知单》，上面有四位查询码会在扫描公证书右下角的二维码后要求输入，日后修改户籍信息要用的！

出行方面，短距离建议直接买高铁商务座，长距离建议买卧铺的下铺（刷不到下铺的可以在售票处点名要下铺），用不到轮椅的我们也没必要申请什么重点旅客，改证前记得把12306app注销了。

改证方面，最容易遇到的扯皮问题就是被说【标题是诊断证明书而不是（性别）鉴定证明书】（尽管最下面确实有社会性别而不是生理性别的鉴定），不过请示上级以后说不定就能当场通过了，三个月有效期的临时身份证还是旧证的照片。

快感方面，插着模具时可以尝试夹紧双腿用手掌摩擦阴阜到阴唇的位置，频率足够高的话就可能达到高潮并喷出白色到透明的液体……

这次流程写到这里就算是完结了，欢迎讨论和提问。

**Comment by septs** [comment]
@LiMee233 
1. 如果家属（父母）无法到场的话，建议公证
2. 模版参照 https://mtf.wiki/zh-cn/docs/srs/china/sh411/icf.pdf
3. 可以发送邮件至 srs-411@mtf.wiki 申请加入术前群

see https://mtf.wiki/zh-cn/docs/srs/china/sh411/
see https://mtf.wiki/zh-cn/docs/friendship/

**Comment by Cryolitia** [comment]
赵博那里似乎根本没有本人知情同意书这个东西

**Comment by cocoAutumn** [comment]
> 本人知情同意书必须公证吗
![IMG_20230605_214158](https://github.com/project-trans/MtF-wiki/assets/88474935/8320b203-21f5-478f-81a3-e3ac3a044db5)
2017标准是要的，2022标准不要了，我全套材料是按照北医三院的要求准备的（应该也是国内最高要求了，包括未婚这个离谱的证明）……

**Comment by LiMee233** [comment]
# 补充

> 时间是自由的，医生和护士可能会根据你的恢复情况和自己的时间决定。各种事情的时间、顺序都可能会改变。

## 入院

关于「术前停止 HRT 一个月」，实际上三周就差不多了，少几天不要太过担心；但安全考虑还是建议足够一个月。

家长知情同意书上，需要写上家长的电话。但不一定会有人去打，似乎看年龄、资金来源或者心情。

家长知情同意书、自己的申请书（可选？）用北医三院的模板就可以，院方似乎不太在意固定格式。

在住院部一楼交待床证和押金后，住院处护士站会有消息，如果你长时间不上去住院，就会打电话催你。所以如果想在外面买东西，就在交待床证和押金之前去。

**其实完全可以不带那么多东西去医院，尤其是不在上海本地的话。因为入院后很可能不是马上手术，可以等到住院后再网购。住院后是可以去门口拿快递和外卖的。**

需要的东西（补充）
1. 小风扇需要可以放在桌子上立着，并能吹到你。我相信不会有人愿意一直举着风扇。
2. 只需要带牙刷、牙膏和一个牙杯，护工阿姨有用来吐漱口水的杯子，也有吸管。
3. 可以考虑带一些一次性筷子，你和阿姨都不会想洗筷子的。
4. 镜子可以不用带，如果带也不要带太小的；可以用举着手机，用相机、闪光灯和延时拍照实现。
5. 6 包抽纸可能不太够，可以考虑多带一些。
6. 手机支架可能不需要买，阿姨那里有一堆。
7. 可以考虑使用分装瓶装少量的洗发水和沐浴露。
8. 浴巾，（不是毛巾，但毛巾也要带啊），浴巾用来垫在屁股底下，下地初期也可以围起来遮住下面。

---

放东西的位置管的没那么严格。

半流食可能是 粥、面条、馄饨。

撕完的纱布线条需要装在一个袋子里面，可以考虑弄个塑料袋。

## 手术

开塞露憋一两分钟就行了，憋不住了就跑去拉掉，会肚子痛。

如果手术当天早晨还没给你弹力袜记得找医生要，之后找护工阿姨帮你穿上。

我全程没有用止痛针，就是止痛泵用完后的几天内会比较痛，按照自己的实际情况来就可以。

换药的时间可能会因为恢复时间有所推迟。

留置针换手的问题不用自己操心，输液输不进去护士会帮你换的。

第一周禁食期间的最后几天，放屁很可能会带出大便，如果出现此情况放心告诉阿姨就好。

第二周的主要不适感，是憋大小便的感觉。

拆包后，可能第二天才会让你下地，请尽可能练习下地不晕，如果一直晕无法下地活动的话，医生就无法给你拆线拔尿管的。如果不幸在 d+14 没能成功下地，那就请在能下地后及时提醒医生，让他给你拆线拔管（因为尿管插着太折磨了）。

6 月 411 就开空调了，如果感觉温度太低，就让阿姨调高点，自己盖好被子吧，不要感冒了。

阿姨会用病号裤、浴巾等垫在屁股下面，比较舒服。

端铁盘吃饭不是不能接受，可以把枕头对折一下，把头垫高，是能吃到的。

---

先写这些，待更新……

**Comment by Cryolitia** [comment]
![8bcb16a0808e6961a09da41824880059](https://github.com/project-trans/MtF-wiki/assets/23723294/5e60fc05-584d-40e7-8584-09d2bd08bab9)
![ec40fdc9e8eb70460b101727d8122d0d](https://github.com/project-trans/MtF-wiki/assets/23723294/21f4d2e5-a96e-4e02-97eb-a183d18c9e69)
更多补充

411页面将在近期进行大幅度修订

**Comment by Cryolitia** [comment]
预征询 
请问 @cocoAutumn @LiMee233 是否需要在主线提交中添加您二为为 [Co-Author](https://docs.github.com/zh/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors)，如果需要的话请提供您二位的电子邮箱地址，详见Github帮助，非常感谢。

**Comment by LiMee233** [comment]
> 预征询 请问 @cocoAutumn @LiMee233 是否需要在主线提交中添加您二为为 [Co-Author](https://docs.github.com/zh/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors)，如果需要的话请提供您二位的电子邮箱地址，详见Github帮助，非常感谢。

Co-authored-by: LiMee233 <LiMee233@outlook.com>

**Comment by LiMee233** [comment]
Co-authored-by: LiMee233 <[LiMee233@outlook.com](mailto:LiMee233@outlook.com)>

**Comment by cocoAutumn** [comment]
Co-authored-by: cocoAutumn <88474935+cocoAutumn@users.noreply.github.com>

**Comment by chatouis** [comment]
过于详细以至于我好像自己经历了一次 SRS 。。。

**Comment by Cryolitia** [comment]
术前停止HRT这个很迷……我在day+0注射最后一针日雌，day+11晨抽血检查，day+17手术，没有被医生提及激素或凝血问题。更令人迷惑的是或许出于可以猜到的目的，术后七天内我被静推了十针「注射用尖吻蝮蛇血凝酶」……

**本回复不构成医疗建议，亦不代表普遍情况，请咨询医生并谨遵医嘱。**

**Comment by el-psy** [comment]
Estrogen and thrombosis: A bench to bedside review
https://sci-hub.hkvisa.net/ 可下载。
我关于HRT和血栓就只知道这些了。
