### ISSUE TITLE
Kamol各术式更新

### ISSUE THREAD

**Issue by KiraRettosei** [project-trans/MtF-wiki#792]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/srs/thailand/kamol/

### 内容

（信息源为向医院页面customercare邮箱发文，而24日Darcie Silver 作为院方的国际协调员给我的回信）
手术费用：
仅阴茎翻转PI THB 321,000
阴囊皮瓣 $11，500 含宿与术前费用
结肠 THB 500,000
结肠腹腔镜 THB630,000
腹膜 THB650,000

手术外费用中，
化验、胸部X光、心电图 涨价到5,600 
核酸检测报告似乎已经不要求

结肠（非腹腔镜）BMI 26 体重 80kg
其他BMI 30 体重90kg

HIV感染者多交30%而不是50%

参见https://docs.google.com/document/d/1EPzRb5KWAknMdlpy-BsOEF-SQo85SooO/edit?usp=share_link&ouid=111169392049405424013&rtpof=true&sd=true

**Comment by saeziae** [comment]
Roger. Reviewing that document.

**Comment by KiraRettosei** [comment]
首次参与编辑，想问一下目前这些新消息是在等待多方检验吗？

**Comment by saeziae** [comment]
你好，泰国手术板块为我一人主要维护，近期较繁忙，我会尽快处理！
如果可以的话，也可以麻烦会操作的朋友直接编辑提交pr，感激不尽！
