### ISSUE TITLE
浙医二院（滨江）- 赵一鸣 孙博 单利珍

### ISSUE THREAD

**Issue by Chobuki** [project-trans/MtF-wiki#796]
### 医院名称

浙江大学医学院附属第二医院（滨江院区）

### 医生姓名

赵一鸣 孙博 单利珍

### 标签

需家长同意

### 可开具的药品

螺内酯, 其他

##### 开具药物处方：
**初诊**时出示回龙观病历，要求开具HRT药物的外配处方；**医生询问家长是否知情并同意激素治疗**，回答是。
**复诊**时直接要求开具处方，无需再次解释。
初次开具某一种药物的处方时医生会询问用法用量等信息并据此开具处方；
要求不同医生开具同一药物的处方时可直接出示已持有的处方，从而节约时间。
注意：**医生仅开具处方和检查，不提供HRT指导**
Ps. 浙二滨江内分泌科医生总体友跨，就诊时不必有过大心理负担。

附回龙观病历参考（建议初诊时携带相关诊断书或病历）：
![IMG_20220922_161438](https://user-images.githubusercontent.com/39644949/235581470-c03531c5-1cb4-4a2a-902c-9add2ace167c.jpg)

##### 激素检查：
直接要求进行激素六项检查即可，价格约240元（可医保报销，额度因人而异）。
检查结果可以在支付宝浙二互联网医院小程序中直接查询，无须打印报告单。

### 可开具的药品（详细）：
下列药物之外的药物，如醋酸环丙孕酮（色谱龙、华典）、戊酸雌二醇片（补佳乐）等，尚不明确是否可以开出处方，相关信息有待补充。
##### 雌二醇凝胶（外配处方；赵一鸣、孙博）：
![IMG_20230502_115625](https://user-images.githubusercontent.com/39644949/235578558-345946b0-8f95-4e83-ac56-c3706f3fc73b.jpg)
![IMG_20230502_115643](https://user-images.githubusercontent.com/39644949/235578575-55be28df-4111-4c66-8868-c696c053db0c.jpg)
![mmexport1683000280760](https://user-images.githubusercontent.com/39644949/235578583-5ecb4a4b-4dbd-4b20-9b50-85b716f1f741.jpg)

##### 螺内酯（外配处方；单利珍）：
![IMG_20230502_115636](https://user-images.githubusercontent.com/39644949/235578603-6cdc031a-dca2-4e7c-84b6-52981d391dda.jpg)

##### 出诊时间：
|医生|出诊科室|出诊时间|挂号费|
|-----|----------|----------|--------|
|赵一鸣|内分泌科专家门诊|每周六全天|50元|
|单利珍|内分泌科专家门诊|每周日上午|25元|
|孙博|内分泌科门诊（普通号）|周一至周日全天|15或17元|

注：普通门诊中特定医生的出诊时间不定，可在分诊台咨询。

##### 挂号渠道：
1. 支付宝浙二互联网医院小程序；
2. 院内自助终端机；
3. 其他（待补充）。

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Cryolitia** [comment]
![Screenshot_20230716-130112.png](https://github.com/project-trans/MtF-wiki/assets/23723294/427fe293-ad87-494b-9b74-bf39ef55e9fb)

https://twitter.com/yinchao_qaq/status/1612032112525479936

**Comment by zhangkui669** [comment]
上午去的滨江潘洁，说是开不了药，让退号了

**Comment by ipadhim** [comment]
不止滨江院区，解放路院区也有赵一鸣医生的号。如果是未成年咨询会增加“咨询HRT”的病例，并且建议家长陪同。在家长陪同的情况下可以开处方，但是医生会强调HRT的危害。

**Comment by Cryolitia** [comment]
![Image_1711439565621](https://github.com/project-trans/MtF-wiki/assets/23723294/15a643ec-a87f-444d-87c2-280f7f661d1e)

done in 1aaec5b415cac0e9294f9aa0085d2955d11b8772 f5b49ee00fea9ed65ce5723568265070f6931b90 28c29dc6aa58a25ff46357c64815fed53f9ba14a c0a1460d90f5c3e14c40b9c87c528104c0929953
