### ISSUE TITLE
在kamol&chet页面上添加每日大于一次手术可能的标注

### ISSUE THREAD

**Issue by tuboshufps** [project-trans/MtF-wiki#801]
据社群反馈，近期chet医生存在一日两台SRS手术的现象
因为一日两台SRS对医生的疲劳性，第二台手术的质量与第一台手术的质量很难做到一致。
考虑到SRS对于mtf的重要性，每个人都希望获得自己医生最好质量的手术。
所以建议在kamol&chet页面上添加相关标注，说明此医生存在每日大于一次SRS手术的可能。如果在该医生处手术，有成为当日第二台手术对象的可能。
（chet饭越恰越烂了）

**Comment by dev-soragoto** [comment]
起因大概是因为有两个人在wih的手术日期撞了,我觉得的确应该标注

**Comment by tonori** [comment]
从中介梁金处询问也得到了一天行多台手术的确认回复
<img width="1249" alt="image" src="https://github.com/project-trans/MtF-wiki/assets/47135403/3f92451a-5ac9-477b-8d16-6e102b1b0699">
