### ISSUE TITLE
未成年卡bug以进行srs的方法,仅供参考

### ISSUE THREAD

**Issue by sourceoflife123** [project-trans/MtF-wiki#818]
## Warning

1. 不建议未成年进行 SRS，但是由于发现很多未成年人自切或黑切，这是很不安全的，所以提供一个未成年 SRS 的方法，目的仅为了干预自杀自切，如不是实在受不了，请不要使用
1. 本方法有阴茎切除，所以会导致性快感下降，请对性敏感性有要求的请谨慎作为参考
1. **仅供参考**，不对该文章造成的后果负责
1. 在 2023 年 6 月 30 日发布，短时间内具有可行性且身边已有成功案例，但不保证长时间时效性

## 思路

由于现在只需要切除性腺及生殖器，便可更改身份证；
所以可以先行性腺及生殖器切除，再进行司法鉴定，更改性别后再行 SRS

**该思路来源于本人朋友，本人自切的，但也通过这种方法成功预约 SRS**

## 第一步 进行生殖器切除

（需要注意，这一步之后将不能通过阴蒂获得性快感）

目前只知道两家医院可以对未成年进行性腺和生殖器（也就是睾丸和阴茎）切除，上海的要求是都要满 18 岁，但是安徽暂时没有这个要求

1. 安徽医科大学第一附属医院 泌尿外科 张贤生\
挂号：周一 周四下午\
要求：易性症证明\
即使成年也不可做 SRS，因为不是整形外科\
此处花费 13,500 元左右\
Warning: 此医院有翻车的案例，即尿道狭窄，由于本方法所需时间较长，大概几个月左右，所以还会对生活有一定影响

2. 安徽医科大学第二附属医院 整形外科 曹东升\
挂号：周一全天\
要求：易性症证明\
此处花费 13,500 元左右\
你甚至可以改完身份证后还去找这个医生 SRS

## 第二步 司法鉴定

建议 复旦大学上海医学院司法鉴定中心 周月琴

电话：021-54230-7559

工作时间：周一至周五 8:30 - 11:30、13:30 - 16:30

建议先打电话预约时间

此处花费1050元,报告大概十几天出

## 第三步 更改身份证

不同地方规定不同,但有司法鉴定证明就可以

## 第四步 SRS

1. 上海九院\
零深度 4w 以内,其它不知道，刘阳也不会建议未成年做有深度手术，但成年以后可以在做
1. 411\
没问过但是身份证都改了应该可以

**Comment by Cryolitia** [comment]
可重复性未知，MtF.wiki 无法鼓励该行为。
