### ISSUE TITLE
关于wiki上学历修改的疑惑

### ISSUE THREAD

**Issue by thelovelymomogirl** [project-trans/MtF-wiki#819]
wiki上学历修改的注意事项已在今年2月3号更新为「据相关消息，毕业学历已无法进行修改，建议在大学本科教育前完成 SRS 并完成[证件变更](https://mtf.wiki/zh-cn/docs/srs/id-card/)」，但是下面仍然保留着完整的修改流程并说其是可修改的内容

2月3号后，还是有能修改成功的可能性的说法，目前我也不是很确定（

所以近半年内有无已毕业学历性别、姓名成功修改的真实案例？如果没有并且真的无法进行修改了，那有没有比较具体的原因？消息来源又是什么？

**Comment by saeziae** [comment]
最早是前辈给出的消息：

https://twitter.com/floria_nyan/status/1599022728526594048

> 从省级教育部门获悉教育部明确要求对于性别变更的情况不再允许毕业后更正学历学位。并有多起更正性别被拒绝的类似报告。

近期有人咨询学校得到的消息是：

https://twitter.com/Nokta_gardisto/status/1654823924084121600

> 去学校改学籍的时候问了下已经毕业的怎么办，学校方面的回复是说不是他们不想帮忙，而是教育部已经三令五申，学校不能管已经毕业的学生的学籍。

因为我们没有检索到明文规定所以 Wiki 并不能下定论说“绝对改不了”

**Comment by Cryolitia** [comment]
![-2f554f7b51839412](https://github.com/project-trans/MtF-wiki/assets/23723294/38f4fdcd-1308-400e-9426-7e6f0383fe6a)

**Comment by BeiyanYunyi** [comment]
我的建议是，加上推里面这张图的一些内容，进行一定的劝解和安慰 https://twitter.com/floria_nyan/status/1599022728526594048

如：

- 选择专业时以区求职时避免相对保守的行业、职业和地区，从而减少持有性别不符的学历的情况下受到歧视的可能性。同理也可以考虑使用 LinkedIn 等途径寻找国外的工作。
- 以新的户籍获得更高级别的学历学位，并在之后只使用这一学历学位。
- 留学。即使是目前已经在国内大学入学，同样可以重新申请转学到国外学校，从而彻底规避国内学历学位的性别问题。此外，也可以申请硕士或博士项目。大部分国家的博士项目（以及一些国家的研究型硕士项目）通常都有丰厚的奖学金，不会带来经济负担。

当前存在[由于此页面内容而焦虑爆炸的案例](https://one-among.us/profile/Mio)，并间接导致了她的自杀。我认为此页面的内容有必要重新加以斟酌。

**Comment by el-psy** [comment]
除非从立法角度，感觉很难。

**Comment by Cryolitia** [comment]
closed by #891
