### ISSUE TITLE
郑州大学第三附属医院（河南省妇幼保健院）可以开具诊断证明

### ISSUE THREAD

**Issue by kosakuraiori** [project-trans/MtF-wiki#825]
### 医院名称

郑州大学第三附属医院（河南省妇幼保健院）

### 医生姓名

段桂琴

### 标签

LGBT+ 友善, 初诊获得证明/假条, 无需抢号/挂号

### 注意事项

最好在郑州大学第三附属医院有ADHD或者ASD相关的证明，我不确定对于单纯想去拿证明的人可不可以直接拿。

### 证明样式

https://drive.google.com/file/d/1kwyM98aYk3BZSdKlM6hx8fN9RxxCnr9o/view?usp=drive_link

### 以 CC-BY-SA 4.0 协议分发

- [x] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Rinfair-CSP-A016** [comment]
基于部分手术可能要求除性别焦虑/抑郁症外无其他精神疾病诊断，你能否确认`有前置的其他诊断`是必需吗？

**Comment by kosakuraiori** [comment]
> 基于部分手术可能要求除性别焦虑/抑郁症外无其他精神疾病诊断，你能否确认`有前置的其他诊断`是必需吗？

该院要求：如果要诊断ICD-11-HA60或者ICD-10-F64.0，需要在本院确诊ADHD/ASD之类的疾病。

并非一般意义上“要求无精神问题”而是要求“必须有ADHD/ASD”之类的“疾病”。

**Comment by Rinfair-CSP-A016** [comment]
请提供诊断证明书的扫描件或使用Microsoft Lens拍摄处理后重新提交，该内容已进入workflow，感谢这一宝贵信息！

**Comment by kosakuraiori** [comment]
> 请提供诊断证明书的扫描件或使用Microsoft Lens拍摄处理后重新提交，该内容已进入workflow，感谢这一宝贵信息！

原件已经被我妈干烂了，我手上有的只有以前拍的照片。


https://s2.loli.net/2023/07/26/4poLiGjCgrfuIQv.jpg

**Comment by kosakuraiori** [comment]
> 请提供诊断证明书的扫描件或使用Microsoft Lens拍摄处理后重新提交，该内容已进入workflow，感谢这一宝贵信息！

Microsoft Lens处理后的版本。

https://1drv.ms/i/s!AkekKh2C_3JQgcJmPgbVE38TOeRczA?e=701zWq

**Comment by SilverHexe** [comment]
如果没有adhd的诊断证明可以在这位医生这里以HRT的理由拿药吗？

**Comment by kosakuraiori** [comment]
> 如果没有adhd的诊断证明可以在这位医生这里以HRT的理由拿药吗？

我没试过

**Comment by kosakuraiori** [comment]
> 请提供诊断证明书的扫描件或使用Microsoft Lens拍摄处理后重新提交，该内容已进入workflow，感谢这一宝贵信息！

扫描件已经提供，位于下方Google Drive链接中。

已经编辑部分信息。

https://drive.google.com/file/d/1kwyM98aYk3BZSdKlM6hx8fN9RxxCnr9o/view?usp=sharing

**Comment by kosakuraiori** [comment]
> 如果没有adhd的诊断证明可以在这位医生这里以HRT的理由拿药吗？

更新：如果你有性别不一致证明且在别的医院有HRT处方，那么，郑州大学第三附属医院（河南省妇幼保健院）的成人内科可以直接开药，不需要专门找她。

**Comment by SilverHexe** [comment]
我没有，我是想去开可以拿药的易性症诊断证明

**Comment by SilverHexe** [comment]
我没有任何处方。。。无证含糖

**Comment by kosakuraiori** [comment]
> 我没有任何处方。。。无证含糖

郑州大学第三附属医院没有相关经验，因此她们拒绝开具处方。但可以根据已有处方开药和检查。

**Comment by SilverHexe** [comment]
明白了，谢谢你的回复！

**Comment by kosakuraiori** [comment]
> 明白了，谢谢你的回复！

如果在河南，我建议直接去北医三院拿HRT处方后，回郑州大学第三附属医院拿药。

**Comment by SilverHexe** [comment]
可能撑不到那个时候，不过还是谢谢你的答复！

**Comment by Cryolitia** [comment]
@kosakuraiori 有其他同级别或更高级别医院的处方去哪都可以开的

**Comment by Cryolitia** [comment]
该 issue 需等待进一步确认。在 MtF.wiki 上登载的医生，其几乎一定会出现短时间内被大量跨性别 DDoS （分布式拒绝服务攻击）的情况。许多医生会在职业生涯上的初次开证后迅速接诊大量跨性别，甚至包括跨省专程前来开证，并可能因此承受相伴随的院方和家属的压力，进而导致其迅速转变为拒绝接诊。因此对于初次报告的医生，我们需要更多案例证明开证的稳定性，同时也包括验证其流程和要求是千篇一律的还是个性化程度非常高的。感谢您的理解与支持。
