### ISSUE TITLE
王小红在父母双方意见不一致时拒绝开药

### ISSUE THREAD

**Issue by ArielHeleneto** [project-trans/MtF-wiki#832]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/hrt/wang-xiaohong/

### 内容

该医生在父母双方意见不一致时拒绝开药，即使一方同意也无效。

2023年7月26就诊，母亲同意父亲有疑问而拒绝开药

**Comment by Rinfair-CSP-A016** [comment]
你是否尝试过只带母亲陪诊？

**Comment by ArielHeleneto** [comment]
> 你是否尝试过只带母亲陪诊？

是的，在只有我妈第一次同意的时候开药了。

但是我爸第二次的时候非要跟着去于是就不开了。
