### ISSUE TITLE
新加坡 Mount Elizabeth 医院的 Alex Fok 医生可以给16岁开HRT治疗

### ISSUE THREAD

**Issue by Z-Siqi** [project-trans/MtF-wiki#834]
### 医院名称

Mount Elizabeth Medical Centre

### 医生姓名

Alex Fok

### 标签

提供 HRT 指导, 需家长同意

### 可开具的药品

戊酸雌二醇, 螺内酯, 其他

### 注意事项

预约前需要先取得Gender Dysphoria (性别烦躁) 诊断，其次如果未满21岁需要父母陪同，但未满16岁或17岁只能使用GnRHa。医生介绍网站：[www.alexfok.com](https://www.alexfok.com/)。

我个人的情况是先去 Private Space Medical 找了  Dr Kwok 获得了诊断，然后让  Dr Kwok 帮忙写推荐信和预约，最后带着父亲和推荐信去找 Alex Fok。需要注意的是父母需要同意，如果父母态度不定会遇到麻烦或，无法获得HRT。

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Rinfair-CSP-A016** [comment]
存在HRT前置检查（如肝功能、肾功能）吗？
从就诊到取得HRT处方总计花费多少？
在医院现场拿药还是自己另行至药店购买？如果是前者，能直接拿到的是什么药物（例如：凝胶、贴片）？

**Comment by Z-Siqi** [comment]
前置需要检查激素水平，已知医院药房没有Androcur，可以拿到Progynova和Aldactone。医院药房买三个月的Progynova价格是138新币，但Aldactone较贵，大概471新币。就诊大概花费是200多新币。因为是私人医疗机构，所以偏贵
