### ISSUE TITLE
寻求信息：四川省华西医院-张岚

### ISSUE THREAD

**Issue by mis1042** [project-trans/MtF-wiki#835]
寻求关于该医生的信息，包括友跨否，开证以及开处方的年龄要求等

![mmexport1690436052440.jpg](https://github.com/project-trans/MtF-wiki/assets/53249654/299569af-52a9-4bd7-b42d-577290e51973)

**Comment by CoelacanthusHex** [comment]
Wiki 作为信息整合平台，我们历史上从未收录过华西医院的医生信息，[未确认列表](https://mtf.wiki/zh-cn/docs/unconfirmed/)中存在其他华西医院医生，但是无更多报告和细节，故我们无法提供答复。你可以在[社交平台](https://twitter.com/search?q=%E5%8D%8E%E8%A5%BF%20%E8%B7%A8%E6%80%A7%E5%88%AB&src=typed_query&f=live)上寻找当地跨性别社群以寻求帮助。
