### ISSUE TITLE
武汉精卫六角亭院区的李赋医生现已转移到二七院区坐诊

### ISSUE THREAD

**Issue by rpOneawa** [project-trans/MtF-wiki#841]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/psyco/hubei/li-fu/

### 内容

根据“武汉市精神卫生中心”公众号上的挂号信息以及李赋医生本人与我的联系，自今年八月起，他已从六角亭院区转移到二七院区坐诊，坐诊时间仍是每周五。

**Comment by LiAlH4-Tr** [comment]
resolved https://github.com/project-trans/MtF-wiki/pull/864
