### ISSUE TITLE
关于说明书更新

### ISSUE THREAD

**Issue by bilibili-xiongge** [project-trans/MtF-wiki#851]
### MtF.wiki URL

https://mtf.wiki/documents/progynon.pdf

### 内容

这个原文说明书与” https://www.fuji-pharma.jp/pd/productdetail/176 “  中新版说明书内容不一致（说明书内容已更新）

**Comment by Bersella-AI** [comment]
非常感谢你的提醒。在附属 TFSci 翻译项目中，已有该针剂说明书的[中文翻译](https://tfsci.mtf.wiki/zh-cn/misc/progynon-depot/)，翻译时间为 [2023 年 4 月 29 日](https://github.com/project-trans/transfeminine-science/commit/5652b25edff692524246789bec47cc23f892c19d)，原文为 2013 年修订。而在 2023 年七月，说明书得到了[新的修订](https://www.fuji-pharma.jp/docs/176/document_176.pdf)，为此我考虑先修订译文，再更新主站相关信息。:+1:

**Comment by Bersella-AI** [comment]
译文已被[更新](https://github.com/project-trans/transfeminine-science/commit/05317d271dce06a07a326b8aef78e6b6d0d7a1d1)，现拟更新由 Wiki 托管的说明书原文：#863

**Comment by Bersella-AI** [comment]
已完成说明书原文的更新。https://github.com/project-trans/MtF-wiki/commit/ae9397f93039a6644e77fc7e6e1efa4925cdf887
