### ISSUE TITLE
广州市第一人民医院-徐利敏医生已停止开证

### ISSUE THREAD

**Issue by lzc256** [project-trans/MtF-wiki#859]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/psyco/guangdong/gzhosp/

### 内容

2023-08-17T10:21+08:00

广州市第一人民医院-徐利敏医生面诊情况：
- 徐利敏医生拒绝接见以开证为目的的跨性别者，不再开具诊断证明，并建议前往其他医院就诊
- 在声明自己的目的是解决焦虑和抑郁状态后，徐利敏医生进行了心理评估并开出抗抑郁药物
- 广州市第一人民医院暂无心理治疗师出诊
- 广州市第一人民医院脑科医疗资源不足，无法进行跨性别心理治疗
- 医生建议前往以下医院的跨性别**专科**门诊就诊：
    - 广东省人民医院（存疑）
    - 中山三院
    - 惠爱医院

**Comment by BeiyanYunyi** [comment]
在 2022 年 6 月就已经有了徐利敏停止开证的消息（由跨性别相关 bot 发布），我是 5 月在她那里开了一个“疑似”的，没想到是末班车……
