### ISSUE TITLE
嗓音女性化手术目录排序问题

### ISSUE THREAD

**Issue by LiAlH4-Tr** [project-trans/MtF-wiki#866]
如图，排序中国内和国外混杂在一起未分离
![Screenshot_2023-08-20-20-34-11-107_com microsoft emmx](https://github.com/project-trans/MtF-wiki/assets/61769640/ccd6f3f6-65db-44a3-abaf-efe5d633ff70)

**Comment by septs** [comment]
> **weight**
>
> used for [ordering your content in lists](https://gohugo.io/templates/lists/). Lower weight gets higher precedence. So content with lower weight will come first. If set, weights should be non-zero, as 0 is interpreted as an unset weight.

from https://gohugo.io/content-management/front-matter/
