### ISSUE TITLE
广州暨南一院 高绿芬 现在提供HRT指导和青春期阻断治疗

### ISSUE THREAD

**Issue by krishukr** [project-trans/MtF-wiki#882]
2023-08-30

- 高医生现在提供 HRT 指导。
- 14 周岁以下可以进行青春期阻断治疗。
- 14 周岁到 16 周岁，已经进行青春期阻断治疗六个月以上的，可以进行 HRT。需要监护人同意。
- 16 周岁到 18 周岁，可以进行 HRT，但是会推荐进行青春期阻断治疗。需要监护人同意。
- 会推荐且可以开出 爱斯妥 和 GnRHa 作为 HRT 药物。
- 会向家长推荐前往广东省生殖医院进行生育力保存。

**Comment by XiangYyang** [comment]
咱的情况可以作为补充（20230830）

**概况**

 * 有被要求填一个「跨性别激素治疗 病历报告表」的东东，在今日抓到的同类里面还有1个被叫填了这个

 * 门诊病历在填完该报告表会多个「处理记录」，大致内容是已告知相关风险以及生育不可逆影响，并签字知情同意书

 * 目前对于18岁以上似乎并没有给父母打电话征询意见什么的情况

**检查**

医生有开具骨密度检查（包括初诊也有开具，咱以前一直以为是复诊才有），凝血四项，常规生化，肝功能三项，血脂五项，血常规五分类，尿液分析以及尿沉淀定量，这些检查费用加起来超过1000元，且缴费不能分开（即不能只交一部分）。

目前几次去的话，基本的内容都包括蛋蛋彩超和乳腺彩超，加上骨密度，这两个加起来大约是870元。今天有遇到同类因为个人经济原因不是很能负担检查的情况，建议手头紧的同类注意下。

最后b超室建议提前问一下林芳芳或者张煜医生在不在，高医生会强烈建议b超让这两位医生做，可能出现不在的情况，导致一天做不完。另推荐自己在别的医院挂全科或者便民门诊找个理由把激素六项（可以只做雌二醇，睾酮，泌乳素）做了把纸质版报告带过去。

**Comment by krishukr** [comment]
补充一点，染色体报告似乎非必须。不过我是之前做了还没出结果。

**Comment by krishukr** [comment]
1 月后复诊

- 未开出任何检查，高医生认为 凝胶 + GnRHa 总体上安全有效，三月复查一次即可。
- 要求填写与初诊时相同的量表。
- 可以添加助手微信或在「好大夫在线」及「暨南大学附属第一医院互联网医院」微信小程序上与高医生取得联系，但似乎无法通过互联网平台开出 HRT 药物。
