### ISSUE TITLE
“脑垂体 HPG 轴体”概念需要明确

### ISSUE THREAD

**Issue by BeiyanYunyi** [project-trans/MtF-wiki#894]
https://github.com/project-trans/MtF-wiki/blob/a91f1787a941c219236d0402c9baf85b8a7f29a3/content/zh-cn/docs/medicine/hrt-overview.md?plain=1#L79C9-L79C46

```markdown
- 临床实验证明，雌激素会破坏脑垂体 HPG 轴体，从而对男性生育能力造成不可逆转的损伤。
```

https://github.com/project-trans/MtF-wiki/blob/a91f1787a941c219236d0402c9baf85b8a7f29a3/content/zh-hant/docs/medicine/hrt-overview.md?plain=1#L75C1-L75C46

```markdown
- 臨床實驗證明，雌激素會破壞腦垂體 HPG 軸體，從而對男性生育能力造成不可逆轉的損傷。
```

“HPG 轴”指下丘脑（hypothalamic）-垂体（pituitary）-性腺（gonadal）轴，“脑垂体 HPG 轴体”概念似不存在。

**Comment by wmtdru8xip** [comment]
Git blame 了一下，显示这是 saeziae 在 wiki 建立初期加入的。

我简单看了一下，好像hrt并不会一定会不可逆转地损害男性生育力，尽管可能性存在；然而，这并不是对下丘脑/垂体的损害导致的。此外，似乎辅助生殖可以帮助绝大多数的人。当然，对于有获得生物学后代意愿者，生育力保存仍然是必要的。

最后，“脑垂体 HPG 轴体”显然是荒谬的。

**Comment by Cryolitia** [comment]
建议对相关内容增补文献

上海四一一医院会对所有经手术切除的睾丸进行病理活检，几乎所有人都有轻度到中度的生精小管萎缩，我个人不认为此过程完全可逆，但也并非一定会导致生育能力永久彻底的丧失。出于事前诸葛，我认为我们应该指出存在不可逆的永久丧失的可能性，并建议有相关考虑的人优先进行生育力保存。

**Comment by Bersella-AI** [comment]
非常感谢以上勘误。《HRT 综述》确实有些时日未曾修订了，我的精力主要集中于外文材料的翻译和诸药品详情的整理上，对于这份综述反而有所疏忽。近期我会结合目前实际医疗需求，酌情重新整理《综述》。:heart:

**Comment by Bersella-AI** [comment]
2023 年 10 月 19  日的提交（https://github.com/project-trans/MtF-wiki/commit/1feb2c01eb24ee6295ebccd5cebcb28fecf8fc16 ）已修复此问题，将进行归档。
