### ISSUE TITLE
“常见法律问题”中“对于具有暴力倾向的跨性别者的建议”有待改进

### ISSUE THREAD

**Issue by BeiyanYunyi** [project-trans/MtF-wiki#898]
https://github.com/project-trans/MtF-wiki/blob/0649712b9cb71c2ad1ea5fe91b0c2d1599cde06c/content/zh-cn/docs/useful-info/legal-faq.md?plain=1#L70

我的观感是，使用了一个不够中立、客观的方式向读者“喊话”。这部分内容与前文乃至整个 wiki 的内容风格都不同，显得突兀。

此外，标题是“对于具有暴力倾向的跨性别者的建议”，建议修改为“对具有违法犯罪倾向的跨性别者的建议”，覆盖更为宽泛。

参考修改方法：

> 根据宪法的规定，中华人民共和国公民在行使自由和权利的时候，不得损害国家的、社会的、集体的利益和其他公民的合法的自由和权利。我们也必须遵守宪法和法律，爱护公共财产，遵守公共秩序，尊重社会公德。中华人民共和国刑法相较于一些其它国家的刑法也更为严格，一旦触犯刑法，当事人将面临牢狱之灾，且会被以身份证性别收监。（若是依法不负刑事责任的精神病人将被采取强制医疗措施）

经过 issue 讨论后我会提出 PR。

**Comment by Cryolitia** [comment]
同意修改此部分表述，建议直接 PR 修改后的内容
