### ISSUE TITLE
陆峥等医生的页面URL已更改

### ISSUE THREAD

**Issue by jinjidechefeng** [project-trans/MtF-wiki#901]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/psyco/shanghai/shmhc/

### 内容

点击该页面的“陆峥”链接时，将会跳转至上海精卫的一个静态页面。http://www.smhc.org.cn/MedicalGuide/contents/48/30.html
![Screenshot_2023_0921_095500](https://github.com/project-trans/MtF-wiki/assets/109347015/d8b82a8d-b8a2-48c5-847f-2abf8ed10ac6)
显示网关错误无法访问，经过多设备测试均为此结果。
在官网的界面中查询到的陆峥为以下链接:
https://www.smhc.org.cn/MedicalGuide/contents/1262/23.html
![Screenshot_2023_0921_100058](https://github.com/project-trans/MtF-wiki/assets/109347015/2f6f2dae-ec4a-4ed1-ab2b-3acc2354dae0)

**Comment by jinjidechefeng** [comment]
其余上海精卫的医生界面也有错误，王飚医生的界面为:https://www.smhc.org.cn/MedicalGuide/contents/1263/49.html，而不是http://www.smhc.org.cn/MedicalGuide/contents/49/56.html
张毅医生的界面为:https://www.smhc.org.cn/MedicalGuide/contents/1263/51.html，而不是http://www.smhc.org.cn/MedicalGuide/contents/49/58.html
刘娜医生的界面为:https://www.smhc.org.cn/MedicalGuide/contents/1264/453.html，而不是http://www.smhc.org.cn/MedicalGuide/contents/51/183.html

**Comment by LiAlH4-Tr** [comment]
> 其余上海精卫的医生界面也有错误，王飚医生的界面为:https://www.smhc.org.cn/MedicalGuide/contents/1263/49.html
> 
> 而不是http://www.smhc.org.cn/MedicalGuide/contents/49/56.html
> 
> 张毅医生的界面为:https://www.smhc.org.cn/MedicalGuide/contents/1263/51.html
> 
> 而不是http://www.smhc.org.cn/MedicalGuide/contents/49/58.html
> 
> 刘娜医生的界面为:https://www.smhc.org.cn/MedicalGuide/contents/1264/453.html
> 
> 而不是http://www.smhc.org.cn/MedicalGuide/contents/51/183.html

已更新
