### ISSUE TITLE
泰补药片改版成了白色

### ISSUE THREAD

**Issue by Hyperion03** [project-trans/MtF-wiki#906]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/medicine/estrogen/estradiol-valerate/

### 内容

泰国补加乐已经药片已经改版成了白色，不再是以前的蓝色药片了。

**Comment by kosakuraiori** [comment]
> ### MtF.wiki URL
> 
> https://mtf.wiki/zh-cn/docs/medicine/estrogen/estradiol-valerate/
> ### 内容
> 
> 泰国补加乐已经药片已经改版成了白色，不再是以前的蓝色药片了。

是的，我现在买到的也是白色的。



<a href="https://smms.app/image/F8SrMVokW23ieCX" target="_blank"><img src="https://s2.loli.net/2023/09/30/F8SrMVokW23ieCX.jpg" /></a>

**Comment by Bersella-AI** [comment]
已知悉，是否方便提供这批“泰补”的批次和生产日期？:thinking:

**Comment by kosakuraiori** [comment]
> 已知悉，是否方便提供这批“泰补”的批次和生产日期？🤔

[[4 057598 012690](https://pertento.fda.moph.go.th/FDA_SEARCH_DRUG/SEARCH_DRUG/pop-up_drug.aspx?Newcode_U=U1DR1C1022640003811C)](https://pertento.fda.moph.go.th/FDA_SEARCH_DRUG/SEARCH_DRUG/pop-up_drug.aspx?Newcode_U=U1DR1C1022640003811C)

**Comment by Bersella-AI** [comment]
已确认德国原厂生产、Jenapharm 分销的 Progynova&reg; 21（2 mg 剂型）采用白色包衣：2023 年八月，Jenapharm 修订了该药的[说明书](https://www.jenapharm.de/download/14/116/2486.pdf)，第六章可见相关描述。从 Androcur（俗称“色普龙”）在多国分销的产品说明书可见，拜耳各分销商之同一名称、同一规格产品性状一致，故“泰补”应适用此规律。

新旧产品之间存在过渡期，考虑在相关信息中补充此项变更。

**Comment by kosakuraiori** [comment]
> 已确认德国原厂生产、Jenapharm 分销的 Progynova® 21（2 mg 剂型）采用白色包衣：2023 年八月，Jenapharm 修订了该药的[说明书](https://www.jenapharm.de/download/14/116/2486.pdf)，第六章可见相关描述。从 Androcur（俗称“色普龙”）在多国分销的产品说明书可见，拜耳各分销商之同一名称、同一规格产品性状一致，故“泰补”应适用此规律。
> 
> 新旧产品之间存在过渡期，考虑在相关信息中补充此项变更。

https://github.com/project-trans/MtF-wiki/issues/825#issuecomment-1741680249

询问无关问题：这个什么时候更新？

**Comment by Bersella-AI** [comment]
相关内容已增补。:heart: https://github.com/project-trans/MtF-wiki/commit/c073429245e74a6dd0488f4bd8048ba4e6f3f7d5
