### ISSUE TITLE
北医三院提交材料后等待开会的时间并非一个月

### ISSUE THREAD

**Issue by LiAlH4-Tr** [project-trans/MtF-wiki#907]
23年4月的知乎文章答主表示四个月之后才给通知去开会

https://zhuanlan.zhihu.com/p/622619315

本人询问潘医生助理后得知提交材料之后需要等待半年到一年

![Screenshot_2023-09-29-14-28-08-094_com.tencent.mm-edit.jpg](https://github.com/project-trans/MtF-wiki/assets/61769640/b085714b-96a6-46df-a80b-86e9e1fce0aa)

**Comment by LiAlH4-Tr** [comment]
现可按上述知乎回答修订页面，也可待本人手术过程完成之后按照本人经历修订，在此征求管理人员之意见

**Comment by LiAlH4-Tr** [comment]
同时页面中描述似乎存在歧义，容易让人误解为“提交材料之后需要等待伦理委员会开会审核，若审核成功则会电话通知本人和家长到现场再开一次会，若审核失败则不会通知”，而不是正确的意思“提交材料之后，等待电话通知本人和家长到现场参加伦理委员会审核”

**Comment by Cryolitia** [comment]
> 材料提交无误后，等待伦理委员会开会审核，正常时效是一个月内。潘医生会给你打电话，通知你即将开会，让你和家长带齐所有材料的原件去北京（时间间隔非常短，只有提前两三天，建议做好准备）。

此表述不存在误解。
---
一般而言，开会拖延时间取决于医院行政人员效率，无法准确预计，建议改为「可能需要等待半年至一年左右的较长时间」

建议手术完成后完全重新撰写北医三院页面，可参考411页面相关修订。

**Comment by LiAlH4-Tr** [comment]
> > 材料提交无误后，等待伦理委员会开会审核，正常时效是一个月内。潘医生会给你打电话，通知你即将开会，让你和家长带齐所有材料的原件去北京（时间间隔非常短，只有提前两三天，建议做好准备）。
> 
> 此表述不存在误解。
> 
> ---
> 
> 一般而言，开会拖延时间取决于医院行政人员效率，无法准确预计，建议改为「可能需要等待半年至一年左右的较长时间」
> 
> ---
> 
> 建议手术完成后完全重新撰写北医三院页面，可参考411页面相关修订。

好的，已提交pr #908
