### ISSUE TITLE
关于王小红的挂号方式

### ISSUE THREAD

**Issue by Ehane114514** [project-trans/MtF-wiki#933]
### 医院名称

成都市温江区人民医院

### 医生姓名

王小红

### 标签

提供 HRT 指导, 有检查项目

### 可开具的药品

戊酸雌二醇, 醋酸环丙孕酮

### 注意事项

挂号方式可以通过成都市温江区人民医院公众号，直接搜索医生名字或者选择内分泌科就能找到。除了挂号方式变了好像跟之前没什么不同（甚至HRT同意书上还是四川省人民医院）

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Cryolitia** [comment]
link to https://github.com/project-trans/MtF-wiki/commit/d9d860c9140cbdf5ac587044ae9f09b176f5d3ee

您好，王小红医生相关页面目前已存在：https://github.com/project-trans/MtF-wiki/blob/master/content/zh-cn/docs/hrt/wang-xiaohong/index.md 。

由于内部记录的不可公开的原因，该页面被暂时撤下，如需对上述页面进行增补，欢迎重新打开本议题。
