### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by Seele0oO** [project-trans/MtF-wiki#951]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/srs/china/sh411/

### 内容

[411流水账](https://t.me/+Zpw7TgHjZW05MzU1) 该链接失效

**Comment by Cryolitia** [comment]
@Seele0oO 我改成private了，因为里面全部非私人内容（风景照etc）都整理到mtfwiki上了，下次修改的时候会顺便删掉这个链接。
