### ISSUE TITLE
苏州市立医院北区HRT

### ISSUE THREAD

**Issue by Baizhi-Angelica** [project-trans/MtF-wiki#952]
### 医院名称

苏州市立医院（北区）

### 医生姓名

鲁婷

### 标签

有检查项目

### 可开具的药品

戊酸雌二醇, 螺内酯

### 注意事项

# 苏州市立医院北区HRT

- **医院：** 苏州市立医院（北区）
- **科室：** 内分泌科 **普通门诊**
- **时间：** 2023年12月14日星期四
- **医生：** 鲁婷

### 问诊细节
进门即自述病史，~~医生听到后主动去关门（好评）~~，然后再详细讲了一下性别不一致的诊断时间以及手术时间。要求医生姐姐帮忙开一个激素六项和两盒戊酸雌二醇（补佳乐）。**医生全过程友好**，还主动问我有没有其他需要开的药，~~甚至问了我的一些经历。~~

在填写病历的时候，**需要选择一些与之相关的症状**，给我选择的是性别发育异常。医生跟我说**放心，我们不会泄露你的数据**，打消了顾虑。

### 挂号
进入医院大厅在自助机器挂号，选择普通门诊，内分泌科。或者在苏周到、健康苏州掌上行 app、微信公众号「苏州卫生 12320」、支付宝「医疗健康-预约挂号」进行预约网上平台挂号。

### 就诊路线
大厅电梯上楼左转，看到一个比较大的护士台，挂号单给予护士录入系统后等待叫号。化验中心和缴费台也在二楼，可以很方便的一站式验血。

> 结合本人在2018年未手术期间以男性身份在市立医院北区开具补佳乐的经历，可以倾向于认为苏州市立医院（北区）的内分泌科普通科室长期能够开具药品、测试激素 以及性别不一致友善。

> 注：以男性身份开具戊酸雌二醇处方时本人使用了丛中的诊断病历，但不是证明。当时也选择的是普通门诊，医生同样非常友善，记忆犹新。~~忘了名字真对不起医生，记得也是个姐姐。~~

### 出诊时间
周次 | 时间 | 科室         | 价格
----|-----|--------------|-----
周四 | 下午 | 内分泌普通门诊 | 12元

![2023-12-14 173330](https://github.com/project-trans/MtF-wiki/assets/52900290/204fc8dd-05cf-43c8-a810-d35f6641c932)

![IMG_5428](https://github.com/project-trans/MtF-wiki/assets/52900290/5eb78d63-f4e5-4b11-86b5-42ca694af4ea)

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Baizhi-Angelica** [comment]
因为已经尝试了pull request，所以本issue更改为closed状态。感谢各位大佬的帮助

**Comment by CoelacanthusHex** [comment]
你好，推荐的流程是不要手动关闭 Issue，而是在 PR 的 message 里面写 fix #NUMBER，这样 PR 合并的时候会自动关闭，并且能保持清晰的 PR 与 Issue 关系

**Comment by CoelacanthusHex** [comment]
> > 你好，推荐的流程是不要手动关闭 Issue，而是在 PR 的 message 里面写 fix #NUMBER，这样 PR 合并的时候会自动关闭，并且能保持清晰的 PR 与 Issue 关系
> 
> 我错了，对不起🔪🧎🩸😭

没什么，第一次参与不熟悉很正常
