### ISSUE TITLE
重新评估广州华侨医院贾艳滨

### ISSUE THREAD

**Issue by mengguyi** [project-trans/MtF-wiki#967]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/psyco/guangdong/jia-yanbin/

### 内容

有报告称广州华侨医院贾艳滨对已持有广脑诊断证明且父母支持的未成年MTF拒绝诊断，且被建议暂停HRT。
![image](https://github.com/project-trans/MtF-wiki/assets/73788063/46852d36-a3a0-4656-8081-4ef5450f5db1)

本人（已成年）带着家长在贾艳滨这里被开了8千多人民币的检查费，检查包含 pet CT 等检查。最终也没有开到证。

**Comment by krishukr** [comment]
图中本人在此。

背景：
本人持有[赵素华](https://mtf.wiki/zh-cn/docs/psyco/guangdong/zhao-suhua/)开具的「性身份障碍」诊断证明。父母态度比较支持。目前在[高绿芬](https://mtf.wiki/zh-cn/docs/hrt/jnuh1/)处进行 HRT 。目前届满半年期，高医生建议再次进行精神心理科评估。因没挂上赵医生的号，前往[贾艳滨](https://mtf.wiki/zh-cn/docs/psyco/guangdong/jia-yanbin/)处就诊。

2024-01-24 UTC+8
「（问家长）你们知道激素治疗的风险吗？_男的_也有乳腺癌的风险的」
「你知道金星吧，金星都不用激素了」
「你现在喉结胡须都没长出来，你可以先停一段时间再感受一下」
「你们去存了精子是吧？有没有问医生这个年龄存的精子以后能不能用？」
「你这个年龄一般不做激素治疗，以性咨询为主。也可以尝试一下心理治疗」
（大意如此）
没打病历。

**Comment by Cryolitia** [comment]
另一个案例：https://fxtwitter.com/glowing_sea/status/1748218344933818544

![image](https://github.com/project-trans/MtF-wiki/assets/23723294/97264d06-43e5-4a8f-84d8-8b454ed8b69a)

**Comment by haig233** [comment]
每个医生都有自己的考量，如果说仅仅只是因为对方不同意就去否定，这也有点偏激了

**Comment by Cryolitia** [comment]
> 每个医生都有自己的考量，如果说仅仅只是因为对方不同意就去否定，这也有点偏激了

我个人认为这个 PR 的措辞还是比较中肯的，您可以协助审阅，如有问题也可一并讨论。如果没有太大争议，我会在近日合并这个 PR，此issue也将一并关闭。

https://github.com/project-trans/MtF-wiki/pull/971
