### ISSUE TITLE
浙江大学医学院附属第二医院内分泌科就诊经验

### ISSUE THREAD

**Issue by ZJU-Progynova** [project-trans/MtF-wiki#986]
### 医院名称

浙江大学医学院附属第二医院

### 医生姓名

曾文衡

### 标签

提供 HRT 指导

### 可开具的药品

其他

### 注意事项

# 浙江大学医学院附属第二医院内分泌科就诊经验

## 重点摘录

1. 浙二医生由于经验缺乏，基本不会主动开具HRT处方。
2. 部分大龄医生反跨，部分年轻女医生友跨。

## 声明

1. 本人性别焦虑较轻，2024.1前往浙大二院陈一萍医生（[杭州｜浙江大学医学院附属第二医院 – MtF.wiki](https://mtf.wiki/zh-cn/docs/psyco/zhejiang/sahzu/)）处诊断结果为“性身份障碍”而非“易性症”，且不伴有任何其他心身类疾病。

2. 本人为浙大在校生，参与的所有涉及跨性别的医疗诊断均穿着女装前往。
3. 浙大二院激素化验时间较长，需要1-3天，建议提前做好化验以免排队。

### 挂号费用

内分泌科普通门诊，挂号费50r（解放路院区），100r（滨江院区），25r（博奥院区）。

### 问诊细节

友跨。

进去之后医生看了长相和性别，马上就知道你是怎么回事，会很亲切地问“你是想做女孩子吗？”

只需要如实回答“是”，然后把激素化验结果给医生看，她立刻就明白，说“你是不是在吃什么药”？

医生可以根据症状描述和激素化验结果判断出双高、双低，并给出合理的hrt指导，例如药量调整、需要监测的指标等。

**本人自行服用激素一个月左右前去问诊，在最后的诊断记录中有“易性症”诊断。**

但是，医生会拒绝开具HRT处方，理由是浙二医生在HRT方面的知识水平还不如[MtF.wiki](https://mtf.wiki/zh-cn/docs/medicine/overview/)和[Shizu's HRT Guide](https://docs.hrt.guide/)。最后她会说，”感觉像你这样想做女孩的男孩越来越多了~你们应该圈内有那种专门的激素治疗参考方案吧……那个东西真的已经很完善了……我们现在对这一块也在不断地学习和提升……你就先按照那个方案来吧然后把几个指标监测一下就行了。”

![就诊记录](https://github.com/project-trans/MtF-wiki/assets/104128324/3cd3ed1c-fc63-4797-aee9-9ff6be83d3ec)

### 问诊细节

反跨，避雷。

如实汇报激素服用情况和化验结果之后，医生会严肃指出HRT对于身体的损伤和负面作用，甚至还会说“男性想变成女生这本身就是违背天理的事，你不应该尝试做出这样的改变”。对于开处方，医生的答复是“给男的开戊酸雌二醇片这处方本来就是不合法的”。

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Cryolitia** [comment]
#796 重复，相关信息已更新
