### ISSUE TITLE
一个地方格式需要修改

### ISSUE THREAD

**Issue by reece00** [project-trans/MtF-wiki#988]
### MtF.wiki URL

https://mtf.wiki/zh-cn/docs/psyco/guangxi/nnswy/

### 内容

罗隽的两行条件没直接明确是“且”还是“或”，建议改为一行文本或对第二行增加前置语句

**Comment by reece00** [comment]
这个证，指的是大证吗？（是的话建议加上）

**Comment by Cryolitia** [comment]
写在wiki上的除了特别说明只能写病历，都是可以开诊断证明的。当然决定权在医生，所以对没有规范化流程的新医生留一些模糊空间没有什么不好。
